// Code generated by 'yaegi extract github.com/cenkalti/backoff/v4'. DO NOT EDIT.

package capsule

import (
	"context"
	"github.com/cenkalti/backoff/v4"
	"go/constant"
	"go/token"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/cenkalti/backoff/v4/backoff"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultInitialInterval":     reflect.ValueOf(backoff.DefaultInitialInterval),
		"DefaultMaxElapsedTime":      reflect.ValueOf(backoff.DefaultMaxElapsedTime),
		"DefaultMaxInterval":         reflect.ValueOf(backoff.DefaultMaxInterval),
		"DefaultMultiplier":          reflect.ValueOf(constant.MakeFromLiteral("1.5", token.FLOAT, 0)),
		"DefaultRandomizationFactor": reflect.ValueOf(constant.MakeFromLiteral("0.5", token.FLOAT, 0)),
		"NewConstantBackOff":         reflect.ValueOf(backoff.NewConstantBackOff),
		"NewExponentialBackOff":      reflect.ValueOf(backoff.NewExponentialBackOff),
		"NewTicker":                  reflect.ValueOf(backoff.NewTicker),
		"NewTickerWithTimer":         reflect.ValueOf(backoff.NewTickerWithTimer),
		"Permanent":                  reflect.ValueOf(backoff.Permanent),
		"Retry":                      reflect.ValueOf(backoff.Retry),
		"RetryNotify":                reflect.ValueOf(backoff.RetryNotify),
		"RetryNotifyWithTimer":       reflect.ValueOf(backoff.RetryNotifyWithTimer),
		"Stop":                       reflect.ValueOf(backoff.Stop),
		"SystemClock":                reflect.ValueOf(&backoff.SystemClock).Elem(),
		"WithClockProvider":          reflect.ValueOf(backoff.WithClockProvider),
		"WithContext":                reflect.ValueOf(backoff.WithContext),
		"WithInitialInterval":        reflect.ValueOf(backoff.WithInitialInterval),
		"WithMaxElapsedTime":         reflect.ValueOf(backoff.WithMaxElapsedTime),
		"WithMaxInterval":            reflect.ValueOf(backoff.WithMaxInterval),
		"WithMaxRetries":             reflect.ValueOf(backoff.WithMaxRetries),
		"WithMultiplier":             reflect.ValueOf(backoff.WithMultiplier),
		"WithRandomizationFactor":    reflect.ValueOf(backoff.WithRandomizationFactor),
		"WithRetryStopDuration":      reflect.ValueOf(backoff.WithRetryStopDuration),

		// type definitions
		"BackOff":                reflect.ValueOf((*backoff.BackOff)(nil)),
		"BackOffContext":         reflect.ValueOf((*backoff.BackOffContext)(nil)),
		"Clock":                  reflect.ValueOf((*backoff.Clock)(nil)),
		"ConstantBackOff":        reflect.ValueOf((*backoff.ConstantBackOff)(nil)),
		"ExponentialBackOff":     reflect.ValueOf((*backoff.ExponentialBackOff)(nil)),
		"ExponentialBackOffOpts": reflect.ValueOf((*backoff.ExponentialBackOffOpts)(nil)),
		"Notify":                 reflect.ValueOf((*backoff.Notify)(nil)),
		"Operation":              reflect.ValueOf((*backoff.Operation)(nil)),
		"PermanentError":         reflect.ValueOf((*backoff.PermanentError)(nil)),
		"StopBackOff":            reflect.ValueOf((*backoff.StopBackOff)(nil)),
		"Ticker":                 reflect.ValueOf((*backoff.Ticker)(nil)),
		"Timer":                  reflect.ValueOf((*backoff.Timer)(nil)),
		"ZeroBackOff":            reflect.ValueOf((*backoff.ZeroBackOff)(nil)),

		// interface wrapper definitions
		"_BackOff":        reflect.ValueOf((*_github_com_cenkalti_backoff_v4_BackOff)(nil)),
		"_BackOffContext": reflect.ValueOf((*_github_com_cenkalti_backoff_v4_BackOffContext)(nil)),
		"_Clock":          reflect.ValueOf((*_github_com_cenkalti_backoff_v4_Clock)(nil)),
		"_Timer":          reflect.ValueOf((*_github_com_cenkalti_backoff_v4_Timer)(nil)),
	}
}

// _github_com_cenkalti_backoff_v4_BackOff is an interface wrapper for BackOff type
type _github_com_cenkalti_backoff_v4_BackOff struct {
	IValue       interface{}
	WNextBackOff func() time.Duration
	WReset       func()
}

func (W _github_com_cenkalti_backoff_v4_BackOff) NextBackOff() time.Duration { return W.WNextBackOff() }
func (W _github_com_cenkalti_backoff_v4_BackOff) Reset()                     { W.WReset() }

// _github_com_cenkalti_backoff_v4_BackOffContext is an interface wrapper for BackOffContext type
type _github_com_cenkalti_backoff_v4_BackOffContext struct {
	IValue       interface{}
	WContext     func() context.Context
	WNextBackOff func() time.Duration
	WReset       func()
}

func (W _github_com_cenkalti_backoff_v4_BackOffContext) Context() context.Context {
	return W.WContext()
}
func (W _github_com_cenkalti_backoff_v4_BackOffContext) NextBackOff() time.Duration {
	return W.WNextBackOff()
}
func (W _github_com_cenkalti_backoff_v4_BackOffContext) Reset() { W.WReset() }

// _github_com_cenkalti_backoff_v4_Clock is an interface wrapper for Clock type
type _github_com_cenkalti_backoff_v4_Clock struct {
	IValue interface{}
	WNow   func() time.Time
}

func (W _github_com_cenkalti_backoff_v4_Clock) Now() time.Time { return W.WNow() }

// _github_com_cenkalti_backoff_v4_Timer is an interface wrapper for Timer type
type _github_com_cenkalti_backoff_v4_Timer struct {
	IValue interface{}
	WC     func() <-chan time.Time
	WStart func(duration time.Duration)
	WStop  func()
}

func (W _github_com_cenkalti_backoff_v4_Timer) C() <-chan time.Time          { return W.WC() }
func (W _github_com_cenkalti_backoff_v4_Timer) Start(duration time.Duration) { W.WStart(duration) }
func (W _github_com_cenkalti_backoff_v4_Timer) Stop()                        { W.WStop() }
