// Code generated by 'yaegi extract go.opentelemetry.io/collector/pdata/plog'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/pdata/plog"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/pdata/plog/plog"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultLogRecordFlags":     reflect.ValueOf(&plog.DefaultLogRecordFlags).Elem(),
		"NewLogRecord":              reflect.ValueOf(plog.NewLogRecord),
		"NewLogRecordSlice":         reflect.ValueOf(plog.NewLogRecordSlice),
		"NewLogs":                   reflect.ValueOf(plog.NewLogs),
		"NewResourceLogs":           reflect.ValueOf(plog.NewResourceLogs),
		"NewResourceLogsSlice":      reflect.ValueOf(plog.NewResourceLogsSlice),
		"NewScopeLogs":              reflect.ValueOf(plog.NewScopeLogs),
		"NewScopeLogsSlice":         reflect.ValueOf(plog.NewScopeLogsSlice),
		"SeverityNumberDebug":       reflect.ValueOf(plog.SeverityNumberDebug),
		"SeverityNumberDebug2":      reflect.ValueOf(plog.SeverityNumberDebug2),
		"SeverityNumberDebug3":      reflect.ValueOf(plog.SeverityNumberDebug3),
		"SeverityNumberDebug4":      reflect.ValueOf(plog.SeverityNumberDebug4),
		"SeverityNumberError":       reflect.ValueOf(plog.SeverityNumberError),
		"SeverityNumberError2":      reflect.ValueOf(plog.SeverityNumberError2),
		"SeverityNumberError3":      reflect.ValueOf(plog.SeverityNumberError3),
		"SeverityNumberError4":      reflect.ValueOf(plog.SeverityNumberError4),
		"SeverityNumberFatal":       reflect.ValueOf(plog.SeverityNumberFatal),
		"SeverityNumberFatal2":      reflect.ValueOf(plog.SeverityNumberFatal2),
		"SeverityNumberFatal3":      reflect.ValueOf(plog.SeverityNumberFatal3),
		"SeverityNumberFatal4":      reflect.ValueOf(plog.SeverityNumberFatal4),
		"SeverityNumberInfo":        reflect.ValueOf(plog.SeverityNumberInfo),
		"SeverityNumberInfo2":       reflect.ValueOf(plog.SeverityNumberInfo2),
		"SeverityNumberInfo3":       reflect.ValueOf(plog.SeverityNumberInfo3),
		"SeverityNumberInfo4":       reflect.ValueOf(plog.SeverityNumberInfo4),
		"SeverityNumberTrace":       reflect.ValueOf(plog.SeverityNumberTrace),
		"SeverityNumberTrace2":      reflect.ValueOf(plog.SeverityNumberTrace2),
		"SeverityNumberTrace3":      reflect.ValueOf(plog.SeverityNumberTrace3),
		"SeverityNumberTrace4":      reflect.ValueOf(plog.SeverityNumberTrace4),
		"SeverityNumberUnspecified": reflect.ValueOf(plog.SeverityNumberUnspecified),
		"SeverityNumberWarn":        reflect.ValueOf(plog.SeverityNumberWarn),
		"SeverityNumberWarn2":       reflect.ValueOf(plog.SeverityNumberWarn2),
		"SeverityNumberWarn3":       reflect.ValueOf(plog.SeverityNumberWarn3),
		"SeverityNumberWarn4":       reflect.ValueOf(plog.SeverityNumberWarn4),

		// type definitions
		"JSONMarshaler":     reflect.ValueOf((*plog.JSONMarshaler)(nil)),
		"JSONUnmarshaler":   reflect.ValueOf((*plog.JSONUnmarshaler)(nil)),
		"LogRecord":         reflect.ValueOf((*plog.LogRecord)(nil)),
		"LogRecordFlags":    reflect.ValueOf((*plog.LogRecordFlags)(nil)),
		"LogRecordSlice":    reflect.ValueOf((*plog.LogRecordSlice)(nil)),
		"Logs":              reflect.ValueOf((*plog.Logs)(nil)),
		"MarshalSizer":      reflect.ValueOf((*plog.MarshalSizer)(nil)),
		"Marshaler":         reflect.ValueOf((*plog.Marshaler)(nil)),
		"ProtoMarshaler":    reflect.ValueOf((*plog.ProtoMarshaler)(nil)),
		"ProtoUnmarshaler":  reflect.ValueOf((*plog.ProtoUnmarshaler)(nil)),
		"ResourceLogs":      reflect.ValueOf((*plog.ResourceLogs)(nil)),
		"ResourceLogsSlice": reflect.ValueOf((*plog.ResourceLogsSlice)(nil)),
		"ScopeLogs":         reflect.ValueOf((*plog.ScopeLogs)(nil)),
		"ScopeLogsSlice":    reflect.ValueOf((*plog.ScopeLogsSlice)(nil)),
		"SeverityNumber":    reflect.ValueOf((*plog.SeverityNumber)(nil)),
		"Sizer":             reflect.ValueOf((*plog.Sizer)(nil)),
		"Unmarshaler":       reflect.ValueOf((*plog.Unmarshaler)(nil)),

		// interface wrapper definitions
		"_MarshalSizer": reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_plog_MarshalSizer)(nil)),
		"_Marshaler":    reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_plog_Marshaler)(nil)),
		"_Sizer":        reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_plog_Sizer)(nil)),
		"_Unmarshaler":  reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_plog_Unmarshaler)(nil)),
	}
}

// _go_opentelemetry_io_collector_pdata_plog_MarshalSizer is an interface wrapper for MarshalSizer type
type _go_opentelemetry_io_collector_pdata_plog_MarshalSizer struct {
	IValue       interface{}
	WLogsSize    func(ld plog.Logs) int
	WMarshalLogs func(ld plog.Logs) ([]byte, error)
}

func (W _go_opentelemetry_io_collector_pdata_plog_MarshalSizer) LogsSize(ld plog.Logs) int {
	return W.WLogsSize(ld)
}
func (W _go_opentelemetry_io_collector_pdata_plog_MarshalSizer) MarshalLogs(ld plog.Logs) ([]byte, error) {
	return W.WMarshalLogs(ld)
}

// _go_opentelemetry_io_collector_pdata_plog_Marshaler is an interface wrapper for Marshaler type
type _go_opentelemetry_io_collector_pdata_plog_Marshaler struct {
	IValue       interface{}
	WMarshalLogs func(ld plog.Logs) ([]byte, error)
}

func (W _go_opentelemetry_io_collector_pdata_plog_Marshaler) MarshalLogs(ld plog.Logs) ([]byte, error) {
	return W.WMarshalLogs(ld)
}

// _go_opentelemetry_io_collector_pdata_plog_Sizer is an interface wrapper for Sizer type
type _go_opentelemetry_io_collector_pdata_plog_Sizer struct {
	IValue    interface{}
	WLogsSize func(ld plog.Logs) int
}

func (W _go_opentelemetry_io_collector_pdata_plog_Sizer) LogsSize(ld plog.Logs) int {
	return W.WLogsSize(ld)
}

// _go_opentelemetry_io_collector_pdata_plog_Unmarshaler is an interface wrapper for Unmarshaler type
type _go_opentelemetry_io_collector_pdata_plog_Unmarshaler struct {
	IValue         interface{}
	WUnmarshalLogs func(buf []byte) (plog.Logs, error)
}

func (W _go_opentelemetry_io_collector_pdata_plog_Unmarshaler) UnmarshalLogs(buf []byte) (plog.Logs, error) {
	return W.WUnmarshalLogs(buf)
}
