// Code generated by 'yaegi extract go.opentelemetry.io/otel/metric'. DO NOT EDIT.

package capsule

import (
	"context"
	"go.opentelemetry.io/otel/metric"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/otel/metric/metric"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewAddConfig":                            reflect.ValueOf(metric.NewAddConfig),
		"NewFloat64CounterConfig":                 reflect.ValueOf(metric.NewFloat64CounterConfig),
		"NewFloat64GaugeConfig":                   reflect.ValueOf(metric.NewFloat64GaugeConfig),
		"NewFloat64HistogramConfig":               reflect.ValueOf(metric.NewFloat64HistogramConfig),
		"NewFloat64ObservableCounterConfig":       reflect.ValueOf(metric.NewFloat64ObservableCounterConfig),
		"NewFloat64ObservableGaugeConfig":         reflect.ValueOf(metric.NewFloat64ObservableGaugeConfig),
		"NewFloat64ObservableUpDownCounterConfig": reflect.ValueOf(metric.NewFloat64ObservableUpDownCounterConfig),
		"NewFloat64UpDownCounterConfig":           reflect.ValueOf(metric.NewFloat64UpDownCounterConfig),
		"NewInt64CounterConfig":                   reflect.ValueOf(metric.NewInt64CounterConfig),
		"NewInt64GaugeConfig":                     reflect.ValueOf(metric.NewInt64GaugeConfig),
		"NewInt64HistogramConfig":                 reflect.ValueOf(metric.NewInt64HistogramConfig),
		"NewInt64ObservableCounterConfig":         reflect.ValueOf(metric.NewInt64ObservableCounterConfig),
		"NewInt64ObservableGaugeConfig":           reflect.ValueOf(metric.NewInt64ObservableGaugeConfig),
		"NewInt64ObservableUpDownCounterConfig":   reflect.ValueOf(metric.NewInt64ObservableUpDownCounterConfig),
		"NewInt64UpDownCounterConfig":             reflect.ValueOf(metric.NewInt64UpDownCounterConfig),
		"NewMeterConfig":                          reflect.ValueOf(metric.NewMeterConfig),
		"NewObserveConfig":                        reflect.ValueOf(metric.NewObserveConfig),
		"NewRecordConfig":                         reflect.ValueOf(metric.NewRecordConfig),
		"WithAttributeSet":                        reflect.ValueOf(metric.WithAttributeSet),
		"WithAttributes":                          reflect.ValueOf(metric.WithAttributes),
		"WithDescription":                         reflect.ValueOf(metric.WithDescription),
		"WithExplicitBucketBoundaries":            reflect.ValueOf(metric.WithExplicitBucketBoundaries),
		"WithFloat64Callback":                     reflect.ValueOf(metric.WithFloat64Callback),
		"WithInstrumentationAttributeSet":         reflect.ValueOf(metric.WithInstrumentationAttributeSet),
		"WithInstrumentationAttributes":           reflect.ValueOf(metric.WithInstrumentationAttributes),
		"WithInstrumentationVersion":              reflect.ValueOf(metric.WithInstrumentationVersion),
		"WithInt64Callback":                       reflect.ValueOf(metric.WithInt64Callback),
		"WithSchemaURL":                           reflect.ValueOf(metric.WithSchemaURL),
		"WithUnit":                                reflect.ValueOf(metric.WithUnit),

		// type definitions
		"AddConfig":                            reflect.ValueOf((*metric.AddConfig)(nil)),
		"AddOption":                            reflect.ValueOf((*metric.AddOption)(nil)),
		"Callback":                             reflect.ValueOf((*metric.Callback)(nil)),
		"Float64Callback":                      reflect.ValueOf((*metric.Float64Callback)(nil)),
		"Float64Counter":                       reflect.ValueOf((*metric.Float64Counter)(nil)),
		"Float64CounterConfig":                 reflect.ValueOf((*metric.Float64CounterConfig)(nil)),
		"Float64CounterOption":                 reflect.ValueOf((*metric.Float64CounterOption)(nil)),
		"Float64Gauge":                         reflect.ValueOf((*metric.Float64Gauge)(nil)),
		"Float64GaugeConfig":                   reflect.ValueOf((*metric.Float64GaugeConfig)(nil)),
		"Float64GaugeOption":                   reflect.ValueOf((*metric.Float64GaugeOption)(nil)),
		"Float64Histogram":                     reflect.ValueOf((*metric.Float64Histogram)(nil)),
		"Float64HistogramConfig":               reflect.ValueOf((*metric.Float64HistogramConfig)(nil)),
		"Float64HistogramOption":               reflect.ValueOf((*metric.Float64HistogramOption)(nil)),
		"Float64Observable":                    reflect.ValueOf((*metric.Float64Observable)(nil)),
		"Float64ObservableCounter":             reflect.ValueOf((*metric.Float64ObservableCounter)(nil)),
		"Float64ObservableCounterConfig":       reflect.ValueOf((*metric.Float64ObservableCounterConfig)(nil)),
		"Float64ObservableCounterOption":       reflect.ValueOf((*metric.Float64ObservableCounterOption)(nil)),
		"Float64ObservableGauge":               reflect.ValueOf((*metric.Float64ObservableGauge)(nil)),
		"Float64ObservableGaugeConfig":         reflect.ValueOf((*metric.Float64ObservableGaugeConfig)(nil)),
		"Float64ObservableGaugeOption":         reflect.ValueOf((*metric.Float64ObservableGaugeOption)(nil)),
		"Float64ObservableOption":              reflect.ValueOf((*metric.Float64ObservableOption)(nil)),
		"Float64ObservableUpDownCounter":       reflect.ValueOf((*metric.Float64ObservableUpDownCounter)(nil)),
		"Float64ObservableUpDownCounterConfig": reflect.ValueOf((*metric.Float64ObservableUpDownCounterConfig)(nil)),
		"Float64ObservableUpDownCounterOption": reflect.ValueOf((*metric.Float64ObservableUpDownCounterOption)(nil)),
		"Float64Observer":                      reflect.ValueOf((*metric.Float64Observer)(nil)),
		"Float64UpDownCounter":                 reflect.ValueOf((*metric.Float64UpDownCounter)(nil)),
		"Float64UpDownCounterConfig":           reflect.ValueOf((*metric.Float64UpDownCounterConfig)(nil)),
		"Float64UpDownCounterOption":           reflect.ValueOf((*metric.Float64UpDownCounterOption)(nil)),
		"HistogramOption":                      reflect.ValueOf((*metric.HistogramOption)(nil)),
		"InstrumentOption":                     reflect.ValueOf((*metric.InstrumentOption)(nil)),
		"Int64Callback":                        reflect.ValueOf((*metric.Int64Callback)(nil)),
		"Int64Counter":                         reflect.ValueOf((*metric.Int64Counter)(nil)),
		"Int64CounterConfig":                   reflect.ValueOf((*metric.Int64CounterConfig)(nil)),
		"Int64CounterOption":                   reflect.ValueOf((*metric.Int64CounterOption)(nil)),
		"Int64Gauge":                           reflect.ValueOf((*metric.Int64Gauge)(nil)),
		"Int64GaugeConfig":                     reflect.ValueOf((*metric.Int64GaugeConfig)(nil)),
		"Int64GaugeOption":                     reflect.ValueOf((*metric.Int64GaugeOption)(nil)),
		"Int64Histogram":                       reflect.ValueOf((*metric.Int64Histogram)(nil)),
		"Int64HistogramConfig":                 reflect.ValueOf((*metric.Int64HistogramConfig)(nil)),
		"Int64HistogramOption":                 reflect.ValueOf((*metric.Int64HistogramOption)(nil)),
		"Int64Observable":                      reflect.ValueOf((*metric.Int64Observable)(nil)),
		"Int64ObservableCounter":               reflect.ValueOf((*metric.Int64ObservableCounter)(nil)),
		"Int64ObservableCounterConfig":         reflect.ValueOf((*metric.Int64ObservableCounterConfig)(nil)),
		"Int64ObservableCounterOption":         reflect.ValueOf((*metric.Int64ObservableCounterOption)(nil)),
		"Int64ObservableGauge":                 reflect.ValueOf((*metric.Int64ObservableGauge)(nil)),
		"Int64ObservableGaugeConfig":           reflect.ValueOf((*metric.Int64ObservableGaugeConfig)(nil)),
		"Int64ObservableGaugeOption":           reflect.ValueOf((*metric.Int64ObservableGaugeOption)(nil)),
		"Int64ObservableOption":                reflect.ValueOf((*metric.Int64ObservableOption)(nil)),
		"Int64ObservableUpDownCounter":         reflect.ValueOf((*metric.Int64ObservableUpDownCounter)(nil)),
		"Int64ObservableUpDownCounterConfig":   reflect.ValueOf((*metric.Int64ObservableUpDownCounterConfig)(nil)),
		"Int64ObservableUpDownCounterOption":   reflect.ValueOf((*metric.Int64ObservableUpDownCounterOption)(nil)),
		"Int64Observer":                        reflect.ValueOf((*metric.Int64Observer)(nil)),
		"Int64UpDownCounter":                   reflect.ValueOf((*metric.Int64UpDownCounter)(nil)),
		"Int64UpDownCounterConfig":             reflect.ValueOf((*metric.Int64UpDownCounterConfig)(nil)),
		"Int64UpDownCounterOption":             reflect.ValueOf((*metric.Int64UpDownCounterOption)(nil)),
		"MeasurementOption":                    reflect.ValueOf((*metric.MeasurementOption)(nil)),
		"Meter":                                reflect.ValueOf((*metric.Meter)(nil)),
		"MeterConfig":                          reflect.ValueOf((*metric.MeterConfig)(nil)),
		"MeterOption":                          reflect.ValueOf((*metric.MeterOption)(nil)),
		"MeterProvider":                        reflect.ValueOf((*metric.MeterProvider)(nil)),
		"Observable":                           reflect.ValueOf((*metric.Observable)(nil)),
		"ObserveConfig":                        reflect.ValueOf((*metric.ObserveConfig)(nil)),
		"ObserveOption":                        reflect.ValueOf((*metric.ObserveOption)(nil)),
		"Observer":                             reflect.ValueOf((*metric.Observer)(nil)),
		"RecordConfig":                         reflect.ValueOf((*metric.RecordConfig)(nil)),
		"RecordOption":                         reflect.ValueOf((*metric.RecordOption)(nil)),
		"Registration":                         reflect.ValueOf((*metric.Registration)(nil)),

		// interface wrapper definitions
		"_AddOption":                            reflect.ValueOf((*_go_opentelemetry_io_otel_metric_AddOption)(nil)),
		"_Float64Counter":                       reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64Counter)(nil)),
		"_Float64CounterOption":                 reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64CounterOption)(nil)),
		"_Float64Gauge":                         reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64Gauge)(nil)),
		"_Float64GaugeOption":                   reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64GaugeOption)(nil)),
		"_Float64Histogram":                     reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64Histogram)(nil)),
		"_Float64HistogramOption":               reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64HistogramOption)(nil)),
		"_Float64Observable":                    reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64Observable)(nil)),
		"_Float64ObservableCounter":             reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64ObservableCounter)(nil)),
		"_Float64ObservableCounterOption":       reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64ObservableCounterOption)(nil)),
		"_Float64ObservableGauge":               reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64ObservableGauge)(nil)),
		"_Float64ObservableGaugeOption":         reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64ObservableGaugeOption)(nil)),
		"_Float64ObservableOption":              reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64ObservableOption)(nil)),
		"_Float64ObservableUpDownCounter":       reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64ObservableUpDownCounter)(nil)),
		"_Float64ObservableUpDownCounterOption": reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64ObservableUpDownCounterOption)(nil)),
		"_Float64Observer":                      reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64Observer)(nil)),
		"_Float64UpDownCounter":                 reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64UpDownCounter)(nil)),
		"_Float64UpDownCounterOption":           reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Float64UpDownCounterOption)(nil)),
		"_HistogramOption":                      reflect.ValueOf((*_go_opentelemetry_io_otel_metric_HistogramOption)(nil)),
		"_InstrumentOption":                     reflect.ValueOf((*_go_opentelemetry_io_otel_metric_InstrumentOption)(nil)),
		"_Int64Counter":                         reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64Counter)(nil)),
		"_Int64CounterOption":                   reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64CounterOption)(nil)),
		"_Int64Gauge":                           reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64Gauge)(nil)),
		"_Int64GaugeOption":                     reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64GaugeOption)(nil)),
		"_Int64Histogram":                       reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64Histogram)(nil)),
		"_Int64HistogramOption":                 reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64HistogramOption)(nil)),
		"_Int64Observable":                      reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64Observable)(nil)),
		"_Int64ObservableCounter":               reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64ObservableCounter)(nil)),
		"_Int64ObservableCounterOption":         reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64ObservableCounterOption)(nil)),
		"_Int64ObservableGauge":                 reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64ObservableGauge)(nil)),
		"_Int64ObservableGaugeOption":           reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64ObservableGaugeOption)(nil)),
		"_Int64ObservableOption":                reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64ObservableOption)(nil)),
		"_Int64ObservableUpDownCounter":         reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64ObservableUpDownCounter)(nil)),
		"_Int64ObservableUpDownCounterOption":   reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64ObservableUpDownCounterOption)(nil)),
		"_Int64Observer":                        reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64Observer)(nil)),
		"_Int64UpDownCounter":                   reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64UpDownCounter)(nil)),
		"_Int64UpDownCounterOption":             reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Int64UpDownCounterOption)(nil)),
		"_MeasurementOption":                    reflect.ValueOf((*_go_opentelemetry_io_otel_metric_MeasurementOption)(nil)),
		"_Meter":                                reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Meter)(nil)),
		"_MeterOption":                          reflect.ValueOf((*_go_opentelemetry_io_otel_metric_MeterOption)(nil)),
		"_MeterProvider":                        reflect.ValueOf((*_go_opentelemetry_io_otel_metric_MeterProvider)(nil)),
		"_Observable":                           reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Observable)(nil)),
		"_ObserveOption":                        reflect.ValueOf((*_go_opentelemetry_io_otel_metric_ObserveOption)(nil)),
		"_Observer":                             reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Observer)(nil)),
		"_RecordOption":                         reflect.ValueOf((*_go_opentelemetry_io_otel_metric_RecordOption)(nil)),
		"_Registration":                         reflect.ValueOf((*_go_opentelemetry_io_otel_metric_Registration)(nil)),
	}
}

// _go_opentelemetry_io_otel_metric_AddOption is an interface wrapper for AddOption type
type _go_opentelemetry_io_otel_metric_AddOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64Counter is an interface wrapper for Float64Counter type
type _go_opentelemetry_io_otel_metric_Float64Counter struct {
	IValue   interface{}
	WAdd     func(ctx context.Context, incr float64, options ...metric.AddOption)
	WEnabled func(a0 context.Context) bool
}

func (W _go_opentelemetry_io_otel_metric_Float64Counter) Add(ctx context.Context, incr float64, options ...metric.AddOption) {
	W.WAdd(ctx, incr, options...)
}
func (W _go_opentelemetry_io_otel_metric_Float64Counter) Enabled(a0 context.Context) bool {
	return W.WEnabled(a0)
}

// _go_opentelemetry_io_otel_metric_Float64CounterOption is an interface wrapper for Float64CounterOption type
type _go_opentelemetry_io_otel_metric_Float64CounterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64Gauge is an interface wrapper for Float64Gauge type
type _go_opentelemetry_io_otel_metric_Float64Gauge struct {
	IValue   interface{}
	WEnabled func(a0 context.Context) bool
	WRecord  func(ctx context.Context, value float64, options ...metric.RecordOption)
}

func (W _go_opentelemetry_io_otel_metric_Float64Gauge) Enabled(a0 context.Context) bool {
	return W.WEnabled(a0)
}
func (W _go_opentelemetry_io_otel_metric_Float64Gauge) Record(ctx context.Context, value float64, options ...metric.RecordOption) {
	W.WRecord(ctx, value, options...)
}

// _go_opentelemetry_io_otel_metric_Float64GaugeOption is an interface wrapper for Float64GaugeOption type
type _go_opentelemetry_io_otel_metric_Float64GaugeOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64Histogram is an interface wrapper for Float64Histogram type
type _go_opentelemetry_io_otel_metric_Float64Histogram struct {
	IValue   interface{}
	WEnabled func(a0 context.Context) bool
	WRecord  func(ctx context.Context, incr float64, options ...metric.RecordOption)
}

func (W _go_opentelemetry_io_otel_metric_Float64Histogram) Enabled(a0 context.Context) bool {
	return W.WEnabled(a0)
}
func (W _go_opentelemetry_io_otel_metric_Float64Histogram) Record(ctx context.Context, incr float64, options ...metric.RecordOption) {
	W.WRecord(ctx, incr, options...)
}

// _go_opentelemetry_io_otel_metric_Float64HistogramOption is an interface wrapper for Float64HistogramOption type
type _go_opentelemetry_io_otel_metric_Float64HistogramOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64Observable is an interface wrapper for Float64Observable type
type _go_opentelemetry_io_otel_metric_Float64Observable struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64ObservableCounter is an interface wrapper for Float64ObservableCounter type
type _go_opentelemetry_io_otel_metric_Float64ObservableCounter struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64ObservableCounterOption is an interface wrapper for Float64ObservableCounterOption type
type _go_opentelemetry_io_otel_metric_Float64ObservableCounterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64ObservableGauge is an interface wrapper for Float64ObservableGauge type
type _go_opentelemetry_io_otel_metric_Float64ObservableGauge struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64ObservableGaugeOption is an interface wrapper for Float64ObservableGaugeOption type
type _go_opentelemetry_io_otel_metric_Float64ObservableGaugeOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64ObservableOption is an interface wrapper for Float64ObservableOption type
type _go_opentelemetry_io_otel_metric_Float64ObservableOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64ObservableUpDownCounter is an interface wrapper for Float64ObservableUpDownCounter type
type _go_opentelemetry_io_otel_metric_Float64ObservableUpDownCounter struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64ObservableUpDownCounterOption is an interface wrapper for Float64ObservableUpDownCounterOption type
type _go_opentelemetry_io_otel_metric_Float64ObservableUpDownCounterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Float64Observer is an interface wrapper for Float64Observer type
type _go_opentelemetry_io_otel_metric_Float64Observer struct {
	IValue   interface{}
	WObserve func(value float64, options ...metric.ObserveOption)
}

func (W _go_opentelemetry_io_otel_metric_Float64Observer) Observe(value float64, options ...metric.ObserveOption) {
	W.WObserve(value, options...)
}

// _go_opentelemetry_io_otel_metric_Float64UpDownCounter is an interface wrapper for Float64UpDownCounter type
type _go_opentelemetry_io_otel_metric_Float64UpDownCounter struct {
	IValue   interface{}
	WAdd     func(ctx context.Context, incr float64, options ...metric.AddOption)
	WEnabled func(a0 context.Context) bool
}

func (W _go_opentelemetry_io_otel_metric_Float64UpDownCounter) Add(ctx context.Context, incr float64, options ...metric.AddOption) {
	W.WAdd(ctx, incr, options...)
}
func (W _go_opentelemetry_io_otel_metric_Float64UpDownCounter) Enabled(a0 context.Context) bool {
	return W.WEnabled(a0)
}

// _go_opentelemetry_io_otel_metric_Float64UpDownCounterOption is an interface wrapper for Float64UpDownCounterOption type
type _go_opentelemetry_io_otel_metric_Float64UpDownCounterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_HistogramOption is an interface wrapper for HistogramOption type
type _go_opentelemetry_io_otel_metric_HistogramOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_InstrumentOption is an interface wrapper for InstrumentOption type
type _go_opentelemetry_io_otel_metric_InstrumentOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64Counter is an interface wrapper for Int64Counter type
type _go_opentelemetry_io_otel_metric_Int64Counter struct {
	IValue   interface{}
	WAdd     func(ctx context.Context, incr int64, options ...metric.AddOption)
	WEnabled func(a0 context.Context) bool
}

func (W _go_opentelemetry_io_otel_metric_Int64Counter) Add(ctx context.Context, incr int64, options ...metric.AddOption) {
	W.WAdd(ctx, incr, options...)
}
func (W _go_opentelemetry_io_otel_metric_Int64Counter) Enabled(a0 context.Context) bool {
	return W.WEnabled(a0)
}

// _go_opentelemetry_io_otel_metric_Int64CounterOption is an interface wrapper for Int64CounterOption type
type _go_opentelemetry_io_otel_metric_Int64CounterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64Gauge is an interface wrapper for Int64Gauge type
type _go_opentelemetry_io_otel_metric_Int64Gauge struct {
	IValue   interface{}
	WEnabled func(a0 context.Context) bool
	WRecord  func(ctx context.Context, value int64, options ...metric.RecordOption)
}

func (W _go_opentelemetry_io_otel_metric_Int64Gauge) Enabled(a0 context.Context) bool {
	return W.WEnabled(a0)
}
func (W _go_opentelemetry_io_otel_metric_Int64Gauge) Record(ctx context.Context, value int64, options ...metric.RecordOption) {
	W.WRecord(ctx, value, options...)
}

// _go_opentelemetry_io_otel_metric_Int64GaugeOption is an interface wrapper for Int64GaugeOption type
type _go_opentelemetry_io_otel_metric_Int64GaugeOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64Histogram is an interface wrapper for Int64Histogram type
type _go_opentelemetry_io_otel_metric_Int64Histogram struct {
	IValue   interface{}
	WEnabled func(a0 context.Context) bool
	WRecord  func(ctx context.Context, incr int64, options ...metric.RecordOption)
}

func (W _go_opentelemetry_io_otel_metric_Int64Histogram) Enabled(a0 context.Context) bool {
	return W.WEnabled(a0)
}
func (W _go_opentelemetry_io_otel_metric_Int64Histogram) Record(ctx context.Context, incr int64, options ...metric.RecordOption) {
	W.WRecord(ctx, incr, options...)
}

// _go_opentelemetry_io_otel_metric_Int64HistogramOption is an interface wrapper for Int64HistogramOption type
type _go_opentelemetry_io_otel_metric_Int64HistogramOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64Observable is an interface wrapper for Int64Observable type
type _go_opentelemetry_io_otel_metric_Int64Observable struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64ObservableCounter is an interface wrapper for Int64ObservableCounter type
type _go_opentelemetry_io_otel_metric_Int64ObservableCounter struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64ObservableCounterOption is an interface wrapper for Int64ObservableCounterOption type
type _go_opentelemetry_io_otel_metric_Int64ObservableCounterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64ObservableGauge is an interface wrapper for Int64ObservableGauge type
type _go_opentelemetry_io_otel_metric_Int64ObservableGauge struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64ObservableGaugeOption is an interface wrapper for Int64ObservableGaugeOption type
type _go_opentelemetry_io_otel_metric_Int64ObservableGaugeOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64ObservableOption is an interface wrapper for Int64ObservableOption type
type _go_opentelemetry_io_otel_metric_Int64ObservableOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64ObservableUpDownCounter is an interface wrapper for Int64ObservableUpDownCounter type
type _go_opentelemetry_io_otel_metric_Int64ObservableUpDownCounter struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64ObservableUpDownCounterOption is an interface wrapper for Int64ObservableUpDownCounterOption type
type _go_opentelemetry_io_otel_metric_Int64ObservableUpDownCounterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Int64Observer is an interface wrapper for Int64Observer type
type _go_opentelemetry_io_otel_metric_Int64Observer struct {
	IValue   interface{}
	WObserve func(value int64, options ...metric.ObserveOption)
}

func (W _go_opentelemetry_io_otel_metric_Int64Observer) Observe(value int64, options ...metric.ObserveOption) {
	W.WObserve(value, options...)
}

// _go_opentelemetry_io_otel_metric_Int64UpDownCounter is an interface wrapper for Int64UpDownCounter type
type _go_opentelemetry_io_otel_metric_Int64UpDownCounter struct {
	IValue   interface{}
	WAdd     func(ctx context.Context, incr int64, options ...metric.AddOption)
	WEnabled func(a0 context.Context) bool
}

func (W _go_opentelemetry_io_otel_metric_Int64UpDownCounter) Add(ctx context.Context, incr int64, options ...metric.AddOption) {
	W.WAdd(ctx, incr, options...)
}
func (W _go_opentelemetry_io_otel_metric_Int64UpDownCounter) Enabled(a0 context.Context) bool {
	return W.WEnabled(a0)
}

// _go_opentelemetry_io_otel_metric_Int64UpDownCounterOption is an interface wrapper for Int64UpDownCounterOption type
type _go_opentelemetry_io_otel_metric_Int64UpDownCounterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_MeasurementOption is an interface wrapper for MeasurementOption type
type _go_opentelemetry_io_otel_metric_MeasurementOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Meter is an interface wrapper for Meter type
type _go_opentelemetry_io_otel_metric_Meter struct {
	IValue                          interface{}
	WFloat64Counter                 func(name string, options ...metric.Float64CounterOption) (metric.Float64Counter, error)
	WFloat64Gauge                   func(name string, options ...metric.Float64GaugeOption) (metric.Float64Gauge, error)
	WFloat64Histogram               func(name string, options ...metric.Float64HistogramOption) (metric.Float64Histogram, error)
	WFloat64ObservableCounter       func(name string, options ...metric.Float64ObservableCounterOption) (metric.Float64ObservableCounter, error)
	WFloat64ObservableGauge         func(name string, options ...metric.Float64ObservableGaugeOption) (metric.Float64ObservableGauge, error)
	WFloat64ObservableUpDownCounter func(name string, options ...metric.Float64ObservableUpDownCounterOption) (metric.Float64ObservableUpDownCounter, error)
	WFloat64UpDownCounter           func(name string, options ...metric.Float64UpDownCounterOption) (metric.Float64UpDownCounter, error)
	WInt64Counter                   func(name string, options ...metric.Int64CounterOption) (metric.Int64Counter, error)
	WInt64Gauge                     func(name string, options ...metric.Int64GaugeOption) (metric.Int64Gauge, error)
	WInt64Histogram                 func(name string, options ...metric.Int64HistogramOption) (metric.Int64Histogram, error)
	WInt64ObservableCounter         func(name string, options ...metric.Int64ObservableCounterOption) (metric.Int64ObservableCounter, error)
	WInt64ObservableGauge           func(name string, options ...metric.Int64ObservableGaugeOption) (metric.Int64ObservableGauge, error)
	WInt64ObservableUpDownCounter   func(name string, options ...metric.Int64ObservableUpDownCounterOption) (metric.Int64ObservableUpDownCounter, error)
	WInt64UpDownCounter             func(name string, options ...metric.Int64UpDownCounterOption) (metric.Int64UpDownCounter, error)
	WRegisterCallback               func(f metric.Callback, instruments ...metric.Observable) (metric.Registration, error)
}

func (W _go_opentelemetry_io_otel_metric_Meter) Float64Counter(name string, options ...metric.Float64CounterOption) (metric.Float64Counter, error) {
	return W.WFloat64Counter(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Float64Gauge(name string, options ...metric.Float64GaugeOption) (metric.Float64Gauge, error) {
	return W.WFloat64Gauge(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Float64Histogram(name string, options ...metric.Float64HistogramOption) (metric.Float64Histogram, error) {
	return W.WFloat64Histogram(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Float64ObservableCounter(name string, options ...metric.Float64ObservableCounterOption) (metric.Float64ObservableCounter, error) {
	return W.WFloat64ObservableCounter(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Float64ObservableGauge(name string, options ...metric.Float64ObservableGaugeOption) (metric.Float64ObservableGauge, error) {
	return W.WFloat64ObservableGauge(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Float64ObservableUpDownCounter(name string, options ...metric.Float64ObservableUpDownCounterOption) (metric.Float64ObservableUpDownCounter, error) {
	return W.WFloat64ObservableUpDownCounter(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Float64UpDownCounter(name string, options ...metric.Float64UpDownCounterOption) (metric.Float64UpDownCounter, error) {
	return W.WFloat64UpDownCounter(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Int64Counter(name string, options ...metric.Int64CounterOption) (metric.Int64Counter, error) {
	return W.WInt64Counter(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Int64Gauge(name string, options ...metric.Int64GaugeOption) (metric.Int64Gauge, error) {
	return W.WInt64Gauge(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Int64Histogram(name string, options ...metric.Int64HistogramOption) (metric.Int64Histogram, error) {
	return W.WInt64Histogram(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Int64ObservableCounter(name string, options ...metric.Int64ObservableCounterOption) (metric.Int64ObservableCounter, error) {
	return W.WInt64ObservableCounter(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Int64ObservableGauge(name string, options ...metric.Int64ObservableGaugeOption) (metric.Int64ObservableGauge, error) {
	return W.WInt64ObservableGauge(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Int64ObservableUpDownCounter(name string, options ...metric.Int64ObservableUpDownCounterOption) (metric.Int64ObservableUpDownCounter, error) {
	return W.WInt64ObservableUpDownCounter(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) Int64UpDownCounter(name string, options ...metric.Int64UpDownCounterOption) (metric.Int64UpDownCounter, error) {
	return W.WInt64UpDownCounter(name, options...)
}
func (W _go_opentelemetry_io_otel_metric_Meter) RegisterCallback(f metric.Callback, instruments ...metric.Observable) (metric.Registration, error) {
	return W.WRegisterCallback(f, instruments...)
}

// _go_opentelemetry_io_otel_metric_MeterOption is an interface wrapper for MeterOption type
type _go_opentelemetry_io_otel_metric_MeterOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_MeterProvider is an interface wrapper for MeterProvider type
type _go_opentelemetry_io_otel_metric_MeterProvider struct {
	IValue interface{}
	WMeter func(name string, opts ...metric.MeterOption) metric.Meter
}

func (W _go_opentelemetry_io_otel_metric_MeterProvider) Meter(name string, opts ...metric.MeterOption) metric.Meter {
	return W.WMeter(name, opts...)
}

// _go_opentelemetry_io_otel_metric_Observable is an interface wrapper for Observable type
type _go_opentelemetry_io_otel_metric_Observable struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_ObserveOption is an interface wrapper for ObserveOption type
type _go_opentelemetry_io_otel_metric_ObserveOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Observer is an interface wrapper for Observer type
type _go_opentelemetry_io_otel_metric_Observer struct {
	IValue          interface{}
	WObserveFloat64 func(obsrv metric.Float64Observable, value float64, opts ...metric.ObserveOption)
	WObserveInt64   func(obsrv metric.Int64Observable, value int64, opts ...metric.ObserveOption)
}

func (W _go_opentelemetry_io_otel_metric_Observer) ObserveFloat64(obsrv metric.Float64Observable, value float64, opts ...metric.ObserveOption) {
	W.WObserveFloat64(obsrv, value, opts...)
}
func (W _go_opentelemetry_io_otel_metric_Observer) ObserveInt64(obsrv metric.Int64Observable, value int64, opts ...metric.ObserveOption) {
	W.WObserveInt64(obsrv, value, opts...)
}

// _go_opentelemetry_io_otel_metric_RecordOption is an interface wrapper for RecordOption type
type _go_opentelemetry_io_otel_metric_RecordOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_metric_Registration is an interface wrapper for Registration type
type _go_opentelemetry_io_otel_metric_Registration struct {
	IValue      interface{}
	WUnregister func() error
}

func (W _go_opentelemetry_io_otel_metric_Registration) Unregister() error { return W.WUnregister() }
