// Code generated by 'yaegi extract go.opentelemetry.io/collector/component'. DO NOT EDIT.

package capsule

import (
	"context"
	"go.opentelemetry.io/collector/component"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/component/component"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"KindConnector":              reflect.ValueOf(&component.KindConnector).Elem(),
		"KindExporter":               reflect.ValueOf(&component.KindExporter).Elem(),
		"KindExtension":              reflect.ValueOf(&component.KindExtension).Elem(),
		"KindProcessor":              reflect.ValueOf(&component.KindProcessor).Elem(),
		"KindReceiver":               reflect.ValueOf(&component.KindReceiver).Elem(),
		"MustNewID":                  reflect.ValueOf(component.MustNewID),
		"MustNewIDWithName":          reflect.ValueOf(component.MustNewIDWithName),
		"MustNewType":                reflect.ValueOf(component.MustNewType),
		"NewDefaultBuildInfo":        reflect.ValueOf(component.NewDefaultBuildInfo),
		"NewID":                      reflect.ValueOf(component.NewID),
		"NewIDWithName":              reflect.ValueOf(component.NewIDWithName),
		"NewType":                    reflect.ValueOf(component.NewType),
		"StabilityLevelAlpha":        reflect.ValueOf(component.StabilityLevelAlpha),
		"StabilityLevelBeta":         reflect.ValueOf(component.StabilityLevelBeta),
		"StabilityLevelDeprecated":   reflect.ValueOf(component.StabilityLevelDeprecated),
		"StabilityLevelDevelopment":  reflect.ValueOf(component.StabilityLevelDevelopment),
		"StabilityLevelStable":       reflect.ValueOf(component.StabilityLevelStable),
		"StabilityLevelUndefined":    reflect.ValueOf(component.StabilityLevelUndefined),
		"StabilityLevelUnmaintained": reflect.ValueOf(component.StabilityLevelUnmaintained),

		// type definitions
		"BuildInfo":               reflect.ValueOf((*component.BuildInfo)(nil)),
		"Component":               reflect.ValueOf((*component.Component)(nil)),
		"Config":                  reflect.ValueOf((*component.Config)(nil)),
		"CreateDefaultConfigFunc": reflect.ValueOf((*component.CreateDefaultConfigFunc)(nil)),
		"Factory":                 reflect.ValueOf((*component.Factory)(nil)),
		"Host":                    reflect.ValueOf((*component.Host)(nil)),
		"ID":                      reflect.ValueOf((*component.ID)(nil)),
		"Kind":                    reflect.ValueOf((*component.Kind)(nil)),
		"ShutdownFunc":            reflect.ValueOf((*component.ShutdownFunc)(nil)),
		"StabilityLevel":          reflect.ValueOf((*component.StabilityLevel)(nil)),
		"StartFunc":               reflect.ValueOf((*component.StartFunc)(nil)),
		"TelemetrySettings":       reflect.ValueOf((*component.TelemetrySettings)(nil)),
		"Type":                    reflect.ValueOf((*component.Type)(nil)),

		// interface wrapper definitions
		"_Component": reflect.ValueOf((*_go_opentelemetry_io_collector_component_Component)(nil)),
		"_Config":    reflect.ValueOf((*_go_opentelemetry_io_collector_component_Config)(nil)),
		"_Factory":   reflect.ValueOf((*_go_opentelemetry_io_collector_component_Factory)(nil)),
		"_Host":      reflect.ValueOf((*_go_opentelemetry_io_collector_component_Host)(nil)),
	}
}

// _go_opentelemetry_io_collector_component_Component is an interface wrapper for Component type
type _go_opentelemetry_io_collector_component_Component struct {
	IValue    interface{}
	WShutdown func(ctx context.Context) error
	WStart    func(ctx context.Context, host component.Host) error
}

func (W _go_opentelemetry_io_collector_component_Component) Shutdown(ctx context.Context) error {
	return W.WShutdown(ctx)
}
func (W _go_opentelemetry_io_collector_component_Component) Start(ctx context.Context, host component.Host) error {
	return W.WStart(ctx, host)
}

// _go_opentelemetry_io_collector_component_Config is an interface wrapper for Config type
type _go_opentelemetry_io_collector_component_Config struct {
	IValue interface{}
}

// _go_opentelemetry_io_collector_component_Factory is an interface wrapper for Factory type
type _go_opentelemetry_io_collector_component_Factory struct {
	IValue               interface{}
	WCreateDefaultConfig func() component.Config
	WType                func() component.Type
}

func (W _go_opentelemetry_io_collector_component_Factory) CreateDefaultConfig() component.Config {
	return W.WCreateDefaultConfig()
}
func (W _go_opentelemetry_io_collector_component_Factory) Type() component.Type { return W.WType() }

// _go_opentelemetry_io_collector_component_Host is an interface wrapper for Host type
type _go_opentelemetry_io_collector_component_Host struct {
	IValue         interface{}
	WGetExtensions func() map[component.ID]component.Component
}

func (W _go_opentelemetry_io_collector_component_Host) GetExtensions() map[component.ID]component.Component {
	return W.WGetExtensions()
}
