// Code generated by 'yaegi extract go.opentelemetry.io/collector/consumer'. DO NOT EDIT.

package capsule

import (
	"context"
	"go.opentelemetry.io/collector/consumer"
	"go.opentelemetry.io/collector/pdata/plog"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/pdata/ptrace"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/consumer/consumer"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewLogs":          reflect.ValueOf(consumer.NewLogs),
		"NewMetrics":       reflect.ValueOf(consumer.NewMetrics),
		"NewTraces":        reflect.ValueOf(consumer.NewTraces),
		"WithCapabilities": reflect.ValueOf(consumer.WithCapabilities),

		// type definitions
		"Capabilities":       reflect.ValueOf((*consumer.Capabilities)(nil)),
		"ConsumeLogsFunc":    reflect.ValueOf((*consumer.ConsumeLogsFunc)(nil)),
		"ConsumeMetricsFunc": reflect.ValueOf((*consumer.ConsumeMetricsFunc)(nil)),
		"ConsumeTracesFunc":  reflect.ValueOf((*consumer.ConsumeTracesFunc)(nil)),
		"Logs":               reflect.ValueOf((*consumer.Logs)(nil)),
		"Metrics":            reflect.ValueOf((*consumer.Metrics)(nil)),
		"Option":             reflect.ValueOf((*consumer.Option)(nil)),
		"Traces":             reflect.ValueOf((*consumer.Traces)(nil)),

		// interface wrapper definitions
		"_Logs":    reflect.ValueOf((*_go_opentelemetry_io_collector_consumer_Logs)(nil)),
		"_Metrics": reflect.ValueOf((*_go_opentelemetry_io_collector_consumer_Metrics)(nil)),
		"_Option":  reflect.ValueOf((*_go_opentelemetry_io_collector_consumer_Option)(nil)),
		"_Traces":  reflect.ValueOf((*_go_opentelemetry_io_collector_consumer_Traces)(nil)),
	}
}

// _go_opentelemetry_io_collector_consumer_Logs is an interface wrapper for Logs type
type _go_opentelemetry_io_collector_consumer_Logs struct {
	IValue        interface{}
	WCapabilities func() consumer.Capabilities
	WConsumeLogs  func(ctx context.Context, ld plog.Logs) error
}

func (W _go_opentelemetry_io_collector_consumer_Logs) Capabilities() consumer.Capabilities {
	return W.WCapabilities()
}
func (W _go_opentelemetry_io_collector_consumer_Logs) ConsumeLogs(ctx context.Context, ld plog.Logs) error {
	return W.WConsumeLogs(ctx, ld)
}

// _go_opentelemetry_io_collector_consumer_Metrics is an interface wrapper for Metrics type
type _go_opentelemetry_io_collector_consumer_Metrics struct {
	IValue          interface{}
	WCapabilities   func() consumer.Capabilities
	WConsumeMetrics func(ctx context.Context, md pmetric.Metrics) error
}

func (W _go_opentelemetry_io_collector_consumer_Metrics) Capabilities() consumer.Capabilities {
	return W.WCapabilities()
}
func (W _go_opentelemetry_io_collector_consumer_Metrics) ConsumeMetrics(ctx context.Context, md pmetric.Metrics) error {
	return W.WConsumeMetrics(ctx, md)
}

// _go_opentelemetry_io_collector_consumer_Option is an interface wrapper for Option type
type _go_opentelemetry_io_collector_consumer_Option struct {
	IValue interface{}
}

// _go_opentelemetry_io_collector_consumer_Traces is an interface wrapper for Traces type
type _go_opentelemetry_io_collector_consumer_Traces struct {
	IValue         interface{}
	WCapabilities  func() consumer.Capabilities
	WConsumeTraces func(ctx context.Context, td ptrace.Traces) error
}

func (W _go_opentelemetry_io_collector_consumer_Traces) Capabilities() consumer.Capabilities {
	return W.WCapabilities()
}
func (W _go_opentelemetry_io_collector_consumer_Traces) ConsumeTraces(ctx context.Context, td ptrace.Traces) error {
	return W.WConsumeTraces(ctx, td)
}
