// Code generated by 'yaegi extract go.opentelemetry.io/collector/consumer/consumererror'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/consumer/consumererror"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/consumer/consumererror/consumererror"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"IsDownstream":      reflect.ValueOf(consumererror.IsDownstream),
		"IsPermanent":       reflect.ValueOf(consumererror.IsPermanent),
		"NewDownstream":     reflect.ValueOf(consumererror.NewDownstream),
		"NewLogs":           reflect.ValueOf(consumererror.NewLogs),
		"NewMetrics":        reflect.ValueOf(consumererror.NewMetrics),
		"NewOTLPGRPCError":  reflect.ValueOf(consumererror.NewOTLPGRPCError),
		"NewOTLPHTTPError":  reflect.ValueOf(consumererror.NewOTLPHTTPError),
		"NewPermanent":      reflect.ValueOf(consumererror.NewPermanent),
		"NewRetryableError": reflect.ValueOf(consumererror.NewRetryableError),
		"NewTraces":         reflect.ValueOf(consumererror.NewTraces),
		"ToGRPCStatus":      reflect.ValueOf(consumererror.ToGRPCStatus),
		"ToHTTPStatus":      reflect.ValueOf(consumererror.ToHTTPStatus),

		// type definitions
		"Error":   reflect.ValueOf((*consumererror.Error)(nil)),
		"Logs":    reflect.ValueOf((*consumererror.Logs)(nil)),
		"Metrics": reflect.ValueOf((*consumererror.Metrics)(nil)),
		"Traces":  reflect.ValueOf((*consumererror.Traces)(nil)),
	}
}
