// Code generated by 'yaegi extract go.opentelemetry.io/collector/pipeline'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/pipeline"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/pipeline/pipeline"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrSignalNotSupported": reflect.ValueOf(&pipeline.ErrSignalNotSupported).Elem(),
		"NewID":                 reflect.ValueOf(pipeline.NewID),
		"NewIDWithName":         reflect.ValueOf(pipeline.NewIDWithName),
		"SignalLogs":            reflect.ValueOf(&pipeline.SignalLogs).Elem(),
		"SignalMetrics":         reflect.ValueOf(&pipeline.SignalMetrics).Elem(),
		"SignalTraces":          reflect.ValueOf(&pipeline.SignalTraces).Elem(),

		// type definitions
		"ID":     reflect.ValueOf((*pipeline.ID)(nil)),
		"Signal": reflect.ValueOf((*pipeline.Signal)(nil)),
	}
}
