// Code generated by 'yaegi extract go.opentelemetry.io/collector/consumer/consumertest'. DO NOT EDIT.

package capsule

import (
	"context"
	"go.opentelemetry.io/collector/consumer"
	"go.opentelemetry.io/collector/consumer/consumertest"
	"go.opentelemetry.io/collector/pdata/plog"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/pdata/pprofile"
	"go.opentelemetry.io/collector/pdata/ptrace"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/consumer/consumertest/consumertest"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewErr": reflect.ValueOf(consumertest.NewErr),
		"NewNop": reflect.ValueOf(consumertest.NewNop),

		// type definitions
		"Consumer":     reflect.ValueOf((*consumertest.Consumer)(nil)),
		"LogsSink":     reflect.ValueOf((*consumertest.LogsSink)(nil)),
		"MetricsSink":  reflect.ValueOf((*consumertest.MetricsSink)(nil)),
		"ProfilesSink": reflect.ValueOf((*consumertest.ProfilesSink)(nil)),
		"TracesSink":   reflect.ValueOf((*consumertest.TracesSink)(nil)),

		// interface wrapper definitions
		"_Consumer": reflect.ValueOf((*_go_opentelemetry_io_collector_consumer_consumertest_Consumer)(nil)),
	}
}

// _go_opentelemetry_io_collector_consumer_consumertest_Consumer is an interface wrapper for Consumer type
type _go_opentelemetry_io_collector_consumer_consumertest_Consumer struct {
	IValue           interface{}
	WCapabilities    func() consumer.Capabilities
	WConsumeLogs     func(a0 context.Context, a1 plog.Logs) error
	WConsumeMetrics  func(a0 context.Context, a1 pmetric.Metrics) error
	WConsumeProfiles func(a0 context.Context, a1 pprofile.Profiles) error
	WConsumeTraces   func(a0 context.Context, a1 ptrace.Traces) error
}

func (W _go_opentelemetry_io_collector_consumer_consumertest_Consumer) Capabilities() consumer.Capabilities {
	return W.WCapabilities()
}
func (W _go_opentelemetry_io_collector_consumer_consumertest_Consumer) ConsumeLogs(a0 context.Context, a1 plog.Logs) error {
	return W.WConsumeLogs(a0, a1)
}
func (W _go_opentelemetry_io_collector_consumer_consumertest_Consumer) ConsumeMetrics(a0 context.Context, a1 pmetric.Metrics) error {
	return W.WConsumeMetrics(a0, a1)
}
func (W _go_opentelemetry_io_collector_consumer_consumertest_Consumer) ConsumeProfiles(a0 context.Context, a1 pprofile.Profiles) error {
	return W.WConsumeProfiles(a0, a1)
}
func (W _go_opentelemetry_io_collector_consumer_consumertest_Consumer) ConsumeTraces(a0 context.Context, a1 ptrace.Traces) error {
	return W.WConsumeTraces(a0, a1)
}
