// Code generated by 'yaegi extract go.opentelemetry.io/collector/config/configtls'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/config/configtls"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/config/configtls/configtls"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewDefaultClientConfig": reflect.ValueOf(configtls.NewDefaultClientConfig),
		"NewDefaultConfig":       reflect.ValueOf(configtls.NewDefaultConfig),
		"NewDefaultServerConfig": reflect.ValueOf(configtls.NewDefaultServerConfig),

		// type definitions
		"ClientConfig": reflect.ValueOf((*configtls.ClientConfig)(nil)),
		"Config":       reflect.ValueOf((*configtls.Config)(nil)),
		"ServerConfig": reflect.ValueOf((*configtls.ServerConfig)(nil)),
		"TPMConfig":    reflect.ValueOf((*configtls.TPMConfig)(nil)),
	}
}
