// Code generated by 'yaegi extract go.opentelemetry.io/collector/pdata/pmetric'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/pdata/pmetric"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/pdata/pmetric/pmetric"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AggregationTemporalityCumulative":        reflect.ValueOf(pmetric.AggregationTemporalityCumulative),
		"AggregationTemporalityDelta":             reflect.ValueOf(pmetric.AggregationTemporalityDelta),
		"AggregationTemporalityUnspecified":       reflect.ValueOf(pmetric.AggregationTemporalityUnspecified),
		"DefaultDataPointFlags":                   reflect.ValueOf(&pmetric.DefaultDataPointFlags).Elem(),
		"ExemplarValueTypeDouble":                 reflect.ValueOf(pmetric.ExemplarValueTypeDouble),
		"ExemplarValueTypeEmpty":                  reflect.ValueOf(pmetric.ExemplarValueTypeEmpty),
		"ExemplarValueTypeInt":                    reflect.ValueOf(pmetric.ExemplarValueTypeInt),
		"MetricTypeEmpty":                         reflect.ValueOf(pmetric.MetricTypeEmpty),
		"MetricTypeExponentialHistogram":          reflect.ValueOf(pmetric.MetricTypeExponentialHistogram),
		"MetricTypeGauge":                         reflect.ValueOf(pmetric.MetricTypeGauge),
		"MetricTypeHistogram":                     reflect.ValueOf(pmetric.MetricTypeHistogram),
		"MetricTypeSum":                           reflect.ValueOf(pmetric.MetricTypeSum),
		"MetricTypeSummary":                       reflect.ValueOf(pmetric.MetricTypeSummary),
		"NewExemplar":                             reflect.ValueOf(pmetric.NewExemplar),
		"NewExemplarSlice":                        reflect.ValueOf(pmetric.NewExemplarSlice),
		"NewExponentialHistogram":                 reflect.ValueOf(pmetric.NewExponentialHistogram),
		"NewExponentialHistogramDataPoint":        reflect.ValueOf(pmetric.NewExponentialHistogramDataPoint),
		"NewExponentialHistogramDataPointBuckets": reflect.ValueOf(pmetric.NewExponentialHistogramDataPointBuckets),
		"NewExponentialHistogramDataPointSlice":   reflect.ValueOf(pmetric.NewExponentialHistogramDataPointSlice),
		"NewGauge":                                reflect.ValueOf(pmetric.NewGauge),
		"NewHistogram":                            reflect.ValueOf(pmetric.NewHistogram),
		"NewHistogramDataPoint":                   reflect.ValueOf(pmetric.NewHistogramDataPoint),
		"NewHistogramDataPointSlice":              reflect.ValueOf(pmetric.NewHistogramDataPointSlice),
		"NewMetric":                               reflect.ValueOf(pmetric.NewMetric),
		"NewMetricSlice":                          reflect.ValueOf(pmetric.NewMetricSlice),
		"NewMetrics":                              reflect.ValueOf(pmetric.NewMetrics),
		"NewNumberDataPoint":                      reflect.ValueOf(pmetric.NewNumberDataPoint),
		"NewNumberDataPointSlice":                 reflect.ValueOf(pmetric.NewNumberDataPointSlice),
		"NewResourceMetrics":                      reflect.ValueOf(pmetric.NewResourceMetrics),
		"NewResourceMetricsSlice":                 reflect.ValueOf(pmetric.NewResourceMetricsSlice),
		"NewScopeMetrics":                         reflect.ValueOf(pmetric.NewScopeMetrics),
		"NewScopeMetricsSlice":                    reflect.ValueOf(pmetric.NewScopeMetricsSlice),
		"NewSum":                                  reflect.ValueOf(pmetric.NewSum),
		"NewSummary":                              reflect.ValueOf(pmetric.NewSummary),
		"NewSummaryDataPoint":                     reflect.ValueOf(pmetric.NewSummaryDataPoint),
		"NewSummaryDataPointSlice":                reflect.ValueOf(pmetric.NewSummaryDataPointSlice),
		"NewSummaryDataPointValueAtQuantile":      reflect.ValueOf(pmetric.NewSummaryDataPointValueAtQuantile),
		"NewSummaryDataPointValueAtQuantileSlice": reflect.ValueOf(pmetric.NewSummaryDataPointValueAtQuantileSlice),
		"NumberDataPointValueTypeDouble":          reflect.ValueOf(pmetric.NumberDataPointValueTypeDouble),
		"NumberDataPointValueTypeEmpty":           reflect.ValueOf(pmetric.NumberDataPointValueTypeEmpty),
		"NumberDataPointValueTypeInt":             reflect.ValueOf(pmetric.NumberDataPointValueTypeInt),

		// type definitions
		"AggregationTemporality":               reflect.ValueOf((*pmetric.AggregationTemporality)(nil)),
		"DataPointFlags":                       reflect.ValueOf((*pmetric.DataPointFlags)(nil)),
		"Exemplar":                             reflect.ValueOf((*pmetric.Exemplar)(nil)),
		"ExemplarSlice":                        reflect.ValueOf((*pmetric.ExemplarSlice)(nil)),
		"ExemplarValueType":                    reflect.ValueOf((*pmetric.ExemplarValueType)(nil)),
		"ExponentialHistogram":                 reflect.ValueOf((*pmetric.ExponentialHistogram)(nil)),
		"ExponentialHistogramDataPoint":        reflect.ValueOf((*pmetric.ExponentialHistogramDataPoint)(nil)),
		"ExponentialHistogramDataPointBuckets": reflect.ValueOf((*pmetric.ExponentialHistogramDataPointBuckets)(nil)),
		"ExponentialHistogramDataPointSlice":   reflect.ValueOf((*pmetric.ExponentialHistogramDataPointSlice)(nil)),
		"Gauge":                                reflect.ValueOf((*pmetric.Gauge)(nil)),
		"Histogram":                            reflect.ValueOf((*pmetric.Histogram)(nil)),
		"HistogramDataPoint":                   reflect.ValueOf((*pmetric.HistogramDataPoint)(nil)),
		"HistogramDataPointSlice":              reflect.ValueOf((*pmetric.HistogramDataPointSlice)(nil)),
		"JSONMarshaler":                        reflect.ValueOf((*pmetric.JSONMarshaler)(nil)),
		"JSONUnmarshaler":                      reflect.ValueOf((*pmetric.JSONUnmarshaler)(nil)),
		"MarshalSizer":                         reflect.ValueOf((*pmetric.MarshalSizer)(nil)),
		"Marshaler":                            reflect.ValueOf((*pmetric.Marshaler)(nil)),
		"Metric":                               reflect.ValueOf((*pmetric.Metric)(nil)),
		"MetricSlice":                          reflect.ValueOf((*pmetric.MetricSlice)(nil)),
		"MetricType":                           reflect.ValueOf((*pmetric.MetricType)(nil)),
		"Metrics":                              reflect.ValueOf((*pmetric.Metrics)(nil)),
		"NumberDataPoint":                      reflect.ValueOf((*pmetric.NumberDataPoint)(nil)),
		"NumberDataPointSlice":                 reflect.ValueOf((*pmetric.NumberDataPointSlice)(nil)),
		"NumberDataPointValueType":             reflect.ValueOf((*pmetric.NumberDataPointValueType)(nil)),
		"ProtoMarshaler":                       reflect.ValueOf((*pmetric.ProtoMarshaler)(nil)),
		"ProtoUnmarshaler":                     reflect.ValueOf((*pmetric.ProtoUnmarshaler)(nil)),
		"ResourceMetrics":                      reflect.ValueOf((*pmetric.ResourceMetrics)(nil)),
		"ResourceMetricsSlice":                 reflect.ValueOf((*pmetric.ResourceMetricsSlice)(nil)),
		"ScopeMetrics":                         reflect.ValueOf((*pmetric.ScopeMetrics)(nil)),
		"ScopeMetricsSlice":                    reflect.ValueOf((*pmetric.ScopeMetricsSlice)(nil)),
		"Sizer":                                reflect.ValueOf((*pmetric.Sizer)(nil)),
		"Sum":                                  reflect.ValueOf((*pmetric.Sum)(nil)),
		"Summary":                              reflect.ValueOf((*pmetric.Summary)(nil)),
		"SummaryDataPoint":                     reflect.ValueOf((*pmetric.SummaryDataPoint)(nil)),
		"SummaryDataPointSlice":                reflect.ValueOf((*pmetric.SummaryDataPointSlice)(nil)),
		"SummaryDataPointValueAtQuantile":      reflect.ValueOf((*pmetric.SummaryDataPointValueAtQuantile)(nil)),
		"SummaryDataPointValueAtQuantileSlice": reflect.ValueOf((*pmetric.SummaryDataPointValueAtQuantileSlice)(nil)),
		"Unmarshaler":                          reflect.ValueOf((*pmetric.Unmarshaler)(nil)),

		// interface wrapper definitions
		"_MarshalSizer": reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_pmetric_MarshalSizer)(nil)),
		"_Marshaler":    reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_pmetric_Marshaler)(nil)),
		"_Sizer":        reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_pmetric_Sizer)(nil)),
		"_Unmarshaler":  reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_pmetric_Unmarshaler)(nil)),
	}
}

// _go_opentelemetry_io_collector_pdata_pmetric_MarshalSizer is an interface wrapper for MarshalSizer type
type _go_opentelemetry_io_collector_pdata_pmetric_MarshalSizer struct {
	IValue          interface{}
	WMarshalMetrics func(md pmetric.Metrics) ([]byte, error)
	WMetricsSize    func(md pmetric.Metrics) int
}

func (W _go_opentelemetry_io_collector_pdata_pmetric_MarshalSizer) MarshalMetrics(md pmetric.Metrics) ([]byte, error) {
	return W.WMarshalMetrics(md)
}
func (W _go_opentelemetry_io_collector_pdata_pmetric_MarshalSizer) MetricsSize(md pmetric.Metrics) int {
	return W.WMetricsSize(md)
}

// _go_opentelemetry_io_collector_pdata_pmetric_Marshaler is an interface wrapper for Marshaler type
type _go_opentelemetry_io_collector_pdata_pmetric_Marshaler struct {
	IValue          interface{}
	WMarshalMetrics func(md pmetric.Metrics) ([]byte, error)
}

func (W _go_opentelemetry_io_collector_pdata_pmetric_Marshaler) MarshalMetrics(md pmetric.Metrics) ([]byte, error) {
	return W.WMarshalMetrics(md)
}

// _go_opentelemetry_io_collector_pdata_pmetric_Sizer is an interface wrapper for Sizer type
type _go_opentelemetry_io_collector_pdata_pmetric_Sizer struct {
	IValue       interface{}
	WMetricsSize func(md pmetric.Metrics) int
}

func (W _go_opentelemetry_io_collector_pdata_pmetric_Sizer) MetricsSize(md pmetric.Metrics) int {
	return W.WMetricsSize(md)
}

// _go_opentelemetry_io_collector_pdata_pmetric_Unmarshaler is an interface wrapper for Unmarshaler type
type _go_opentelemetry_io_collector_pdata_pmetric_Unmarshaler struct {
	IValue            interface{}
	WUnmarshalMetrics func(buf []byte) (pmetric.Metrics, error)
}

func (W _go_opentelemetry_io_collector_pdata_pmetric_Unmarshaler) UnmarshalMetrics(buf []byte) (pmetric.Metrics, error) {
	return W.WUnmarshalMetrics(buf)
}
