// Code generated by 'yaegi extract go.opentelemetry.io/collector/config/configtelemetry'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/config/configtelemetry"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/config/configtelemetry/configtelemetry"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"LevelBasic":    reflect.ValueOf(configtelemetry.LevelBasic),
		"LevelDetailed": reflect.ValueOf(configtelemetry.LevelDetailed),
		"LevelNone":     reflect.ValueOf(configtelemetry.LevelNone),
		"LevelNormal":   reflect.ValueOf(configtelemetry.LevelNormal),

		// type definitions
		"Level": reflect.ValueOf((*configtelemetry.Level)(nil)),
	}
}
