// Code generated by 'yaegi extract go.opentelemetry.io/collector/receiver/receiverhelper'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/receiver/receiverhelper"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/receiver/receiverhelper/receiverhelper"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewObsReport":           reflect.ValueOf(receiverhelper.NewObsReport),
		"NewReceiverMetricsGate": reflect.ValueOf(&receiverhelper.NewReceiverMetricsGate).Elem(),

		// type definitions
		"ObsReport":         reflect.ValueOf((*receiverhelper.ObsReport)(nil)),
		"ObsReportSettings": reflect.ValueOf((*receiverhelper.ObsReportSettings)(nil)),
	}
}
