// Code generated by 'yaegi extract go.opentelemetry.io/collector/confmap'. DO NOT EDIT.

package capsule

import (
	"context"
	"go.opentelemetry.io/collector/confmap"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/confmap/confmap"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"KeyDelimiter":         reflect.ValueOf(&confmap.KeyDelimiter).Elem(),
		"MapstructureTag":      reflect.ValueOf(&confmap.MapstructureTag).Elem(),
		"New":                  reflect.ValueOf(confmap.New),
		"NewConverterFactory":  reflect.ValueOf(confmap.NewConverterFactory),
		"NewFromStringMap":     reflect.ValueOf(confmap.NewFromStringMap),
		"NewProviderFactory":   reflect.ValueOf(confmap.NewProviderFactory),
		"NewResolver":          reflect.ValueOf(confmap.NewResolver),
		"NewRetrieved":         reflect.ValueOf(confmap.NewRetrieved),
		"NewRetrievedFromYAML": reflect.ValueOf(confmap.NewRetrievedFromYAML),
		"WithIgnoreUnused":     reflect.ValueOf(confmap.WithIgnoreUnused),
		"WithRetrievedClose":   reflect.ValueOf(confmap.WithRetrievedClose),

		// type definitions
		"ChangeEvent":         reflect.ValueOf((*confmap.ChangeEvent)(nil)),
		"CloseFunc":           reflect.ValueOf((*confmap.CloseFunc)(nil)),
		"Conf":                reflect.ValueOf((*confmap.Conf)(nil)),
		"Converter":           reflect.ValueOf((*confmap.Converter)(nil)),
		"ConverterFactory":    reflect.ValueOf((*confmap.ConverterFactory)(nil)),
		"ConverterSettings":   reflect.ValueOf((*confmap.ConverterSettings)(nil)),
		"CreateConverterFunc": reflect.ValueOf((*confmap.CreateConverterFunc)(nil)),
		"CreateProviderFunc":  reflect.ValueOf((*confmap.CreateProviderFunc)(nil)),
		"MarshalOption":       reflect.ValueOf((*confmap.MarshalOption)(nil)),
		"Marshaler":           reflect.ValueOf((*confmap.Marshaler)(nil)),
		"Provider":            reflect.ValueOf((*confmap.Provider)(nil)),
		"ProviderFactory":     reflect.ValueOf((*confmap.ProviderFactory)(nil)),
		"ProviderSettings":    reflect.ValueOf((*confmap.ProviderSettings)(nil)),
		"Resolver":            reflect.ValueOf((*confmap.Resolver)(nil)),
		"ResolverSettings":    reflect.ValueOf((*confmap.ResolverSettings)(nil)),
		"Retrieved":           reflect.ValueOf((*confmap.Retrieved)(nil)),
		"RetrievedOption":     reflect.ValueOf((*confmap.RetrievedOption)(nil)),
		"UnmarshalOption":     reflect.ValueOf((*confmap.UnmarshalOption)(nil)),
		"Unmarshaler":         reflect.ValueOf((*confmap.Unmarshaler)(nil)),
		"WatcherFunc":         reflect.ValueOf((*confmap.WatcherFunc)(nil)),

		// interface wrapper definitions
		"_Converter":        reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_Converter)(nil)),
		"_ConverterFactory": reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_ConverterFactory)(nil)),
		"_MarshalOption":    reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_MarshalOption)(nil)),
		"_Marshaler":        reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_Marshaler)(nil)),
		"_Provider":         reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_Provider)(nil)),
		"_ProviderFactory":  reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_ProviderFactory)(nil)),
		"_RetrievedOption":  reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_RetrievedOption)(nil)),
		"_UnmarshalOption":  reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_UnmarshalOption)(nil)),
		"_Unmarshaler":      reflect.ValueOf((*_go_opentelemetry_io_collector_confmap_Unmarshaler)(nil)),
	}
}

// _go_opentelemetry_io_collector_confmap_Converter is an interface wrapper for Converter type
type _go_opentelemetry_io_collector_confmap_Converter struct {
	IValue   interface{}
	WConvert func(ctx context.Context, conf *confmap.Conf) error
}

func (W _go_opentelemetry_io_collector_confmap_Converter) Convert(ctx context.Context, conf *confmap.Conf) error {
	return W.WConvert(ctx, conf)
}

// _go_opentelemetry_io_collector_confmap_ConverterFactory is an interface wrapper for ConverterFactory type
type _go_opentelemetry_io_collector_confmap_ConverterFactory struct {
	IValue  interface{}
	WCreate func(s confmap.ConverterSettings) confmap.Converter
}

func (W _go_opentelemetry_io_collector_confmap_ConverterFactory) Create(s confmap.ConverterSettings) confmap.Converter {
	return W.WCreate(s)
}

// _go_opentelemetry_io_collector_confmap_MarshalOption is an interface wrapper for MarshalOption type
type _go_opentelemetry_io_collector_confmap_MarshalOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_collector_confmap_Marshaler is an interface wrapper for Marshaler type
type _go_opentelemetry_io_collector_confmap_Marshaler struct {
	IValue   interface{}
	WMarshal func(component *confmap.Conf) error
}

func (W _go_opentelemetry_io_collector_confmap_Marshaler) Marshal(component *confmap.Conf) error {
	return W.WMarshal(component)
}

// _go_opentelemetry_io_collector_confmap_Provider is an interface wrapper for Provider type
type _go_opentelemetry_io_collector_confmap_Provider struct {
	IValue    interface{}
	WRetrieve func(ctx context.Context, uri string, watcher confmap.WatcherFunc) (*confmap.Retrieved, error)
	WScheme   func() string
	WShutdown func(ctx context.Context) error
}

func (W _go_opentelemetry_io_collector_confmap_Provider) Retrieve(ctx context.Context, uri string, watcher confmap.WatcherFunc) (*confmap.Retrieved, error) {
	return W.WRetrieve(ctx, uri, watcher)
}
func (W _go_opentelemetry_io_collector_confmap_Provider) Scheme() string { return W.WScheme() }
func (W _go_opentelemetry_io_collector_confmap_Provider) Shutdown(ctx context.Context) error {
	return W.WShutdown(ctx)
}

// _go_opentelemetry_io_collector_confmap_ProviderFactory is an interface wrapper for ProviderFactory type
type _go_opentelemetry_io_collector_confmap_ProviderFactory struct {
	IValue  interface{}
	WCreate func(s confmap.ProviderSettings) confmap.Provider
}

func (W _go_opentelemetry_io_collector_confmap_ProviderFactory) Create(s confmap.ProviderSettings) confmap.Provider {
	return W.WCreate(s)
}

// _go_opentelemetry_io_collector_confmap_RetrievedOption is an interface wrapper for RetrievedOption type
type _go_opentelemetry_io_collector_confmap_RetrievedOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_collector_confmap_UnmarshalOption is an interface wrapper for UnmarshalOption type
type _go_opentelemetry_io_collector_confmap_UnmarshalOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_collector_confmap_Unmarshaler is an interface wrapper for Unmarshaler type
type _go_opentelemetry_io_collector_confmap_Unmarshaler struct {
	IValue     interface{}
	WUnmarshal func(component *confmap.Conf) error
}

func (W _go_opentelemetry_io_collector_confmap_Unmarshaler) Unmarshal(component *confmap.Conf) error {
	return W.WUnmarshal(component)
}
