// Code generated by 'yaegi extract go.opentelemetry.io/collector/pdata/ptrace'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/pdata/ptrace"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/pdata/ptrace/ptrace"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewResourceSpans":      reflect.ValueOf(ptrace.NewResourceSpans),
		"NewResourceSpansSlice": reflect.ValueOf(ptrace.NewResourceSpansSlice),
		"NewScopeSpans":         reflect.ValueOf(ptrace.NewScopeSpans),
		"NewScopeSpansSlice":    reflect.ValueOf(ptrace.NewScopeSpansSlice),
		"NewSpan":               reflect.ValueOf(ptrace.NewSpan),
		"NewSpanEvent":          reflect.ValueOf(ptrace.NewSpanEvent),
		"NewSpanEventSlice":     reflect.ValueOf(ptrace.NewSpanEventSlice),
		"NewSpanLink":           reflect.ValueOf(ptrace.NewSpanLink),
		"NewSpanLinkSlice":      reflect.ValueOf(ptrace.NewSpanLinkSlice),
		"NewSpanSlice":          reflect.ValueOf(ptrace.NewSpanSlice),
		"NewStatus":             reflect.ValueOf(ptrace.NewStatus),
		"NewTraces":             reflect.ValueOf(ptrace.NewTraces),
		"SpanKindClient":        reflect.ValueOf(ptrace.SpanKindClient),
		"SpanKindConsumer":      reflect.ValueOf(ptrace.SpanKindConsumer),
		"SpanKindInternal":      reflect.ValueOf(ptrace.SpanKindInternal),
		"SpanKindProducer":      reflect.ValueOf(ptrace.SpanKindProducer),
		"SpanKindServer":        reflect.ValueOf(ptrace.SpanKindServer),
		"SpanKindUnspecified":   reflect.ValueOf(ptrace.SpanKindUnspecified),
		"StatusCodeError":       reflect.ValueOf(ptrace.StatusCodeError),
		"StatusCodeOk":          reflect.ValueOf(ptrace.StatusCodeOk),
		"StatusCodeUnset":       reflect.ValueOf(ptrace.StatusCodeUnset),

		// type definitions
		"JSONMarshaler":      reflect.ValueOf((*ptrace.JSONMarshaler)(nil)),
		"JSONUnmarshaler":    reflect.ValueOf((*ptrace.JSONUnmarshaler)(nil)),
		"MarshalSizer":       reflect.ValueOf((*ptrace.MarshalSizer)(nil)),
		"Marshaler":          reflect.ValueOf((*ptrace.Marshaler)(nil)),
		"ProtoMarshaler":     reflect.ValueOf((*ptrace.ProtoMarshaler)(nil)),
		"ProtoUnmarshaler":   reflect.ValueOf((*ptrace.ProtoUnmarshaler)(nil)),
		"ResourceSpans":      reflect.ValueOf((*ptrace.ResourceSpans)(nil)),
		"ResourceSpansSlice": reflect.ValueOf((*ptrace.ResourceSpansSlice)(nil)),
		"ScopeSpans":         reflect.ValueOf((*ptrace.ScopeSpans)(nil)),
		"ScopeSpansSlice":    reflect.ValueOf((*ptrace.ScopeSpansSlice)(nil)),
		"Sizer":              reflect.ValueOf((*ptrace.Sizer)(nil)),
		"Span":               reflect.ValueOf((*ptrace.Span)(nil)),
		"SpanEvent":          reflect.ValueOf((*ptrace.SpanEvent)(nil)),
		"SpanEventSlice":     reflect.ValueOf((*ptrace.SpanEventSlice)(nil)),
		"SpanKind":           reflect.ValueOf((*ptrace.SpanKind)(nil)),
		"SpanLink":           reflect.ValueOf((*ptrace.SpanLink)(nil)),
		"SpanLinkSlice":      reflect.ValueOf((*ptrace.SpanLinkSlice)(nil)),
		"SpanSlice":          reflect.ValueOf((*ptrace.SpanSlice)(nil)),
		"Status":             reflect.ValueOf((*ptrace.Status)(nil)),
		"StatusCode":         reflect.ValueOf((*ptrace.StatusCode)(nil)),
		"Traces":             reflect.ValueOf((*ptrace.Traces)(nil)),
		"Unmarshaler":        reflect.ValueOf((*ptrace.Unmarshaler)(nil)),

		// interface wrapper definitions
		"_MarshalSizer": reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_ptrace_MarshalSizer)(nil)),
		"_Marshaler":    reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_ptrace_Marshaler)(nil)),
		"_Sizer":        reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_ptrace_Sizer)(nil)),
		"_Unmarshaler":  reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_ptrace_Unmarshaler)(nil)),
	}
}

// _go_opentelemetry_io_collector_pdata_ptrace_MarshalSizer is an interface wrapper for MarshalSizer type
type _go_opentelemetry_io_collector_pdata_ptrace_MarshalSizer struct {
	IValue         interface{}
	WMarshalTraces func(td ptrace.Traces) ([]byte, error)
	WTracesSize    func(td ptrace.Traces) int
}

func (W _go_opentelemetry_io_collector_pdata_ptrace_MarshalSizer) MarshalTraces(td ptrace.Traces) ([]byte, error) {
	return W.WMarshalTraces(td)
}
func (W _go_opentelemetry_io_collector_pdata_ptrace_MarshalSizer) TracesSize(td ptrace.Traces) int {
	return W.WTracesSize(td)
}

// _go_opentelemetry_io_collector_pdata_ptrace_Marshaler is an interface wrapper for Marshaler type
type _go_opentelemetry_io_collector_pdata_ptrace_Marshaler struct {
	IValue         interface{}
	WMarshalTraces func(td ptrace.Traces) ([]byte, error)
}

func (W _go_opentelemetry_io_collector_pdata_ptrace_Marshaler) MarshalTraces(td ptrace.Traces) ([]byte, error) {
	return W.WMarshalTraces(td)
}

// _go_opentelemetry_io_collector_pdata_ptrace_Sizer is an interface wrapper for Sizer type
type _go_opentelemetry_io_collector_pdata_ptrace_Sizer struct {
	IValue      interface{}
	WTracesSize func(td ptrace.Traces) int
}

func (W _go_opentelemetry_io_collector_pdata_ptrace_Sizer) TracesSize(td ptrace.Traces) int {
	return W.WTracesSize(td)
}

// _go_opentelemetry_io_collector_pdata_ptrace_Unmarshaler is an interface wrapper for Unmarshaler type
type _go_opentelemetry_io_collector_pdata_ptrace_Unmarshaler struct {
	IValue           interface{}
	WUnmarshalTraces func(buf []byte) (ptrace.Traces, error)
}

func (W _go_opentelemetry_io_collector_pdata_ptrace_Unmarshaler) UnmarshalTraces(buf []byte) (ptrace.Traces, error) {
	return W.WUnmarshalTraces(buf)
}
