// Code generated by 'yaegi extract go.opentelemetry.io/collector/receiver'. DO NOT EDIT.

package capsule

import (
	"context"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/consumer"
	"go.opentelemetry.io/collector/receiver"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/receiver/receiver"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewFactory":  reflect.ValueOf(receiver.NewFactory),
		"WithLogs":    reflect.ValueOf(receiver.WithLogs),
		"WithMetrics": reflect.ValueOf(receiver.WithMetrics),
		"WithTraces":  reflect.ValueOf(receiver.WithTraces),

		// type definitions
		"CreateLogsFunc":    reflect.ValueOf((*receiver.CreateLogsFunc)(nil)),
		"CreateMetricsFunc": reflect.ValueOf((*receiver.CreateMetricsFunc)(nil)),
		"CreateTracesFunc":  reflect.ValueOf((*receiver.CreateTracesFunc)(nil)),
		"Factory":           reflect.ValueOf((*receiver.Factory)(nil)),
		"FactoryOption":     reflect.ValueOf((*receiver.FactoryOption)(nil)),
		"Logs":              reflect.ValueOf((*receiver.Logs)(nil)),
		"Metrics":           reflect.ValueOf((*receiver.Metrics)(nil)),
		"Settings":          reflect.ValueOf((*receiver.Settings)(nil)),
		"Traces":            reflect.ValueOf((*receiver.Traces)(nil)),

		// interface wrapper definitions
		"_Factory":       reflect.ValueOf((*_go_opentelemetry_io_collector_receiver_Factory)(nil)),
		"_FactoryOption": reflect.ValueOf((*_go_opentelemetry_io_collector_receiver_FactoryOption)(nil)),
		"_Logs":          reflect.ValueOf((*_go_opentelemetry_io_collector_receiver_Logs)(nil)),
		"_Metrics":       reflect.ValueOf((*_go_opentelemetry_io_collector_receiver_Metrics)(nil)),
		"_Traces":        reflect.ValueOf((*_go_opentelemetry_io_collector_receiver_Traces)(nil)),
	}
}

// _go_opentelemetry_io_collector_receiver_Factory is an interface wrapper for Factory type
type _go_opentelemetry_io_collector_receiver_Factory struct {
	IValue               interface{}
	WCreateDefaultConfig func() component.Config
	WCreateLogs          func(ctx context.Context, set receiver.Settings, cfg component.Config, next consumer.Logs) (receiver.Logs, error)
	WCreateMetrics       func(ctx context.Context, set receiver.Settings, cfg component.Config, next consumer.Metrics) (receiver.Metrics, error)
	WCreateTraces        func(ctx context.Context, set receiver.Settings, cfg component.Config, next consumer.Traces) (receiver.Traces, error)
	WLogsStability       func() component.StabilityLevel
	WMetricsStability    func() component.StabilityLevel
	WTracesStability     func() component.StabilityLevel
	WType                func() component.Type
}

func (W _go_opentelemetry_io_collector_receiver_Factory) CreateDefaultConfig() component.Config {
	return W.WCreateDefaultConfig()
}
func (W _go_opentelemetry_io_collector_receiver_Factory) CreateLogs(ctx context.Context, set receiver.Settings, cfg component.Config, next consumer.Logs) (receiver.Logs, error) {
	return W.WCreateLogs(ctx, set, cfg, next)
}
func (W _go_opentelemetry_io_collector_receiver_Factory) CreateMetrics(ctx context.Context, set receiver.Settings, cfg component.Config, next consumer.Metrics) (receiver.Metrics, error) {
	return W.WCreateMetrics(ctx, set, cfg, next)
}
func (W _go_opentelemetry_io_collector_receiver_Factory) CreateTraces(ctx context.Context, set receiver.Settings, cfg component.Config, next consumer.Traces) (receiver.Traces, error) {
	return W.WCreateTraces(ctx, set, cfg, next)
}
func (W _go_opentelemetry_io_collector_receiver_Factory) LogsStability() component.StabilityLevel {
	return W.WLogsStability()
}
func (W _go_opentelemetry_io_collector_receiver_Factory) MetricsStability() component.StabilityLevel {
	return W.WMetricsStability()
}
func (W _go_opentelemetry_io_collector_receiver_Factory) TracesStability() component.StabilityLevel {
	return W.WTracesStability()
}
func (W _go_opentelemetry_io_collector_receiver_Factory) Type() component.Type { return W.WType() }

// _go_opentelemetry_io_collector_receiver_FactoryOption is an interface wrapper for FactoryOption type
type _go_opentelemetry_io_collector_receiver_FactoryOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_collector_receiver_Logs is an interface wrapper for Logs type
type _go_opentelemetry_io_collector_receiver_Logs struct {
	IValue    interface{}
	WShutdown func(ctx context.Context) error
	WStart    func(ctx context.Context, host component.Host) error
}

func (W _go_opentelemetry_io_collector_receiver_Logs) Shutdown(ctx context.Context) error {
	return W.WShutdown(ctx)
}
func (W _go_opentelemetry_io_collector_receiver_Logs) Start(ctx context.Context, host component.Host) error {
	return W.WStart(ctx, host)
}

// _go_opentelemetry_io_collector_receiver_Metrics is an interface wrapper for Metrics type
type _go_opentelemetry_io_collector_receiver_Metrics struct {
	IValue    interface{}
	WShutdown func(ctx context.Context) error
	WStart    func(ctx context.Context, host component.Host) error
}

func (W _go_opentelemetry_io_collector_receiver_Metrics) Shutdown(ctx context.Context) error {
	return W.WShutdown(ctx)
}
func (W _go_opentelemetry_io_collector_receiver_Metrics) Start(ctx context.Context, host component.Host) error {
	return W.WStart(ctx, host)
}

// _go_opentelemetry_io_collector_receiver_Traces is an interface wrapper for Traces type
type _go_opentelemetry_io_collector_receiver_Traces struct {
	IValue    interface{}
	WShutdown func(ctx context.Context) error
	WStart    func(ctx context.Context, host component.Host) error
}

func (W _go_opentelemetry_io_collector_receiver_Traces) Shutdown(ctx context.Context) error {
	return W.WShutdown(ctx)
}
func (W _go_opentelemetry_io_collector_receiver_Traces) Start(ctx context.Context, host component.Host) error {
	return W.WStart(ctx, host)
}
