// Code generated by 'yaegi extract go.opentelemetry.io/collector/pdata/pcommon'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/pdata/pcommon/pcommon"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewByteSlice":            reflect.ValueOf(pcommon.NewByteSlice),
		"NewFloat64Slice":         reflect.ValueOf(pcommon.NewFloat64Slice),
		"NewInstrumentationScope": reflect.ValueOf(pcommon.NewInstrumentationScope),
		"NewInt32Slice":           reflect.ValueOf(pcommon.NewInt32Slice),
		"NewInt64Slice":           reflect.ValueOf(pcommon.NewInt64Slice),
		"NewMap":                  reflect.ValueOf(pcommon.NewMap),
		"NewResource":             reflect.ValueOf(pcommon.NewResource),
		"NewSlice":                reflect.ValueOf(pcommon.NewSlice),
		"NewSpanIDEmpty":          reflect.ValueOf(pcommon.NewSpanIDEmpty),
		"NewStringSlice":          reflect.ValueOf(pcommon.NewStringSlice),
		"NewTimestampFromTime":    reflect.ValueOf(pcommon.NewTimestampFromTime),
		"NewTraceIDEmpty":         reflect.ValueOf(pcommon.NewTraceIDEmpty),
		"NewTraceState":           reflect.ValueOf(pcommon.NewTraceState),
		"NewUInt64Slice":          reflect.ValueOf(pcommon.NewUInt64Slice),
		"NewValueBool":            reflect.ValueOf(pcommon.NewValueBool),
		"NewValueBytes":           reflect.ValueOf(pcommon.NewValueBytes),
		"NewValueDouble":          reflect.ValueOf(pcommon.NewValueDouble),
		"NewValueEmpty":           reflect.ValueOf(pcommon.NewValueEmpty),
		"NewValueInt":             reflect.ValueOf(pcommon.NewValueInt),
		"NewValueMap":             reflect.ValueOf(pcommon.NewValueMap),
		"NewValueSlice":           reflect.ValueOf(pcommon.NewValueSlice),
		"NewValueStr":             reflect.ValueOf(pcommon.NewValueStr),
		"ValueTypeBool":           reflect.ValueOf(pcommon.ValueTypeBool),
		"ValueTypeBytes":          reflect.ValueOf(pcommon.ValueTypeBytes),
		"ValueTypeDouble":         reflect.ValueOf(pcommon.ValueTypeDouble),
		"ValueTypeEmpty":          reflect.ValueOf(pcommon.ValueTypeEmpty),
		"ValueTypeInt":            reflect.ValueOf(pcommon.ValueTypeInt),
		"ValueTypeMap":            reflect.ValueOf(pcommon.ValueTypeMap),
		"ValueTypeSlice":          reflect.ValueOf(pcommon.ValueTypeSlice),
		"ValueTypeStr":            reflect.ValueOf(pcommon.ValueTypeStr),

		// type definitions
		"ByteSlice":            reflect.ValueOf((*pcommon.ByteSlice)(nil)),
		"Float64Slice":         reflect.ValueOf((*pcommon.Float64Slice)(nil)),
		"InstrumentationScope": reflect.ValueOf((*pcommon.InstrumentationScope)(nil)),
		"Int32Slice":           reflect.ValueOf((*pcommon.Int32Slice)(nil)),
		"Int64Slice":           reflect.ValueOf((*pcommon.Int64Slice)(nil)),
		"Map":                  reflect.ValueOf((*pcommon.Map)(nil)),
		"Resource":             reflect.ValueOf((*pcommon.Resource)(nil)),
		"Slice":                reflect.ValueOf((*pcommon.Slice)(nil)),
		"SpanID":               reflect.ValueOf((*pcommon.SpanID)(nil)),
		"StringSlice":          reflect.ValueOf((*pcommon.StringSlice)(nil)),
		"Timestamp":            reflect.ValueOf((*pcommon.Timestamp)(nil)),
		"TraceID":              reflect.ValueOf((*pcommon.TraceID)(nil)),
		"TraceState":           reflect.ValueOf((*pcommon.TraceState)(nil)),
		"UInt64Slice":          reflect.ValueOf((*pcommon.UInt64Slice)(nil)),
		"Value":                reflect.ValueOf((*pcommon.Value)(nil)),
		"ValueType":            reflect.ValueOf((*pcommon.ValueType)(nil)),
	}
}
