// Code generated by 'yaegi extract go.opentelemetry.io/otel'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/otel"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/otel/otel"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetErrorHandler":      reflect.ValueOf(otel.GetErrorHandler),
		"GetMeterProvider":     reflect.ValueOf(otel.GetMeterProvider),
		"GetTextMapPropagator": reflect.ValueOf(otel.GetTextMapPropagator),
		"GetTracerProvider":    reflect.ValueOf(otel.GetTracerProvider),
		"Handle":               reflect.ValueOf(otel.Handle),
		"Meter":                reflect.ValueOf(otel.Meter),
		"SetErrorHandler":      reflect.ValueOf(otel.SetErrorHandler),
		"SetLogger":            reflect.ValueOf(otel.SetLogger),
		"SetMeterProvider":     reflect.ValueOf(otel.SetMeterProvider),
		"SetTextMapPropagator": reflect.ValueOf(otel.SetTextMapPropagator),
		"SetTracerProvider":    reflect.ValueOf(otel.SetTracerProvider),
		"Tracer":               reflect.ValueOf(otel.Tracer),
		"Version":              reflect.ValueOf(otel.Version),

		// type definitions
		"ErrorHandler":     reflect.ValueOf((*otel.ErrorHandler)(nil)),
		"ErrorHandlerFunc": reflect.ValueOf((*otel.ErrorHandlerFunc)(nil)),

		// interface wrapper definitions
		"_ErrorHandler": reflect.ValueOf((*_go_opentelemetry_io_otel_ErrorHandler)(nil)),
	}
}

// _go_opentelemetry_io_otel_ErrorHandler is an interface wrapper for ErrorHandler type
type _go_opentelemetry_io_otel_ErrorHandler struct {
	IValue  interface{}
	WHandle func(a0 error)
}

func (W _go_opentelemetry_io_otel_ErrorHandler) Handle(a0 error) { W.WHandle(a0) }
