// Code generated by 'yaegi extract go.opentelemetry.io/collector/pdata/pprofile'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/pdata/pprofile"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/pdata/pprofile/pprofile"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AggregationTemporalityCumulative":  reflect.ValueOf(pprofile.AggregationTemporalityCumulative),
		"AggregationTemporalityDelta":       reflect.ValueOf(pprofile.AggregationTemporalityDelta),
		"AggregationTemporalityUnspecified": reflect.ValueOf(pprofile.AggregationTemporalityUnspecified),
		"FromAttributeIndices":              reflect.ValueOf(pprofile.FromAttributeIndices),
		"FromLocationIndices":               reflect.ValueOf(pprofile.FromLocationIndices),
		"NewFunction":                       reflect.ValueOf(pprofile.NewFunction),
		"NewFunctionSlice":                  reflect.ValueOf(pprofile.NewFunctionSlice),
		"NewKeyValueAndUnit":                reflect.ValueOf(pprofile.NewKeyValueAndUnit),
		"NewKeyValueAndUnitSlice":           reflect.ValueOf(pprofile.NewKeyValueAndUnitSlice),
		"NewLine":                           reflect.ValueOf(pprofile.NewLine),
		"NewLineSlice":                      reflect.ValueOf(pprofile.NewLineSlice),
		"NewLink":                           reflect.ValueOf(pprofile.NewLink),
		"NewLinkSlice":                      reflect.ValueOf(pprofile.NewLinkSlice),
		"NewLocation":                       reflect.ValueOf(pprofile.NewLocation),
		"NewLocationSlice":                  reflect.ValueOf(pprofile.NewLocationSlice),
		"NewMapping":                        reflect.ValueOf(pprofile.NewMapping),
		"NewMappingSlice":                   reflect.ValueOf(pprofile.NewMappingSlice),
		"NewProfile":                        reflect.ValueOf(pprofile.NewProfile),
		"NewProfileIDEmpty":                 reflect.ValueOf(pprofile.NewProfileIDEmpty),
		"NewProfiles":                       reflect.ValueOf(pprofile.NewProfiles),
		"NewProfilesData":                   reflect.ValueOf(pprofile.NewProfilesData),
		"NewProfilesDictionary":             reflect.ValueOf(pprofile.NewProfilesDictionary),
		"NewProfilesSlice":                  reflect.ValueOf(pprofile.NewProfilesSlice),
		"NewResourceProfiles":               reflect.ValueOf(pprofile.NewResourceProfiles),
		"NewResourceProfilesSlice":          reflect.ValueOf(pprofile.NewResourceProfilesSlice),
		"NewSample":                         reflect.ValueOf(pprofile.NewSample),
		"NewSampleSlice":                    reflect.ValueOf(pprofile.NewSampleSlice),
		"NewScopeProfiles":                  reflect.ValueOf(pprofile.NewScopeProfiles),
		"NewScopeProfilesSlice":             reflect.ValueOf(pprofile.NewScopeProfilesSlice),
		"NewStack":                          reflect.ValueOf(pprofile.NewStack),
		"NewStackSlice":                     reflect.ValueOf(pprofile.NewStackSlice),
		"NewValueType":                      reflect.ValueOf(pprofile.NewValueType),
		"NewValueTypeSlice":                 reflect.ValueOf(pprofile.NewValueTypeSlice),
		"SetAttribute":                      reflect.ValueOf(pprofile.SetAttribute),
		"SetFunction":                       reflect.ValueOf(pprofile.SetFunction),
		"SetLink":                           reflect.ValueOf(pprofile.SetLink),
		"SetLocation":                       reflect.ValueOf(pprofile.SetLocation),
		"SetMapping":                        reflect.ValueOf(pprofile.SetMapping),
		"SetStack":                          reflect.ValueOf(pprofile.SetStack),
		"SetString":                         reflect.ValueOf(pprofile.SetString),

		// type definitions
		"AggregationTemporality": reflect.ValueOf((*pprofile.AggregationTemporality)(nil)),
		"Function":               reflect.ValueOf((*pprofile.Function)(nil)),
		"FunctionSlice":          reflect.ValueOf((*pprofile.FunctionSlice)(nil)),
		"JSONMarshaler":          reflect.ValueOf((*pprofile.JSONMarshaler)(nil)),
		"JSONUnmarshaler":        reflect.ValueOf((*pprofile.JSONUnmarshaler)(nil)),
		"KeyValueAndUnit":        reflect.ValueOf((*pprofile.KeyValueAndUnit)(nil)),
		"KeyValueAndUnitSlice":   reflect.ValueOf((*pprofile.KeyValueAndUnitSlice)(nil)),
		"Line":                   reflect.ValueOf((*pprofile.Line)(nil)),
		"LineSlice":              reflect.ValueOf((*pprofile.LineSlice)(nil)),
		"Link":                   reflect.ValueOf((*pprofile.Link)(nil)),
		"LinkSlice":              reflect.ValueOf((*pprofile.LinkSlice)(nil)),
		"Location":               reflect.ValueOf((*pprofile.Location)(nil)),
		"LocationSlice":          reflect.ValueOf((*pprofile.LocationSlice)(nil)),
		"Mapping":                reflect.ValueOf((*pprofile.Mapping)(nil)),
		"MappingSlice":           reflect.ValueOf((*pprofile.MappingSlice)(nil)),
		"MarshalSizer":           reflect.ValueOf((*pprofile.MarshalSizer)(nil)),
		"Marshaler":              reflect.ValueOf((*pprofile.Marshaler)(nil)),
		"Profile":                reflect.ValueOf((*pprofile.Profile)(nil)),
		"ProfileID":              reflect.ValueOf((*pprofile.ProfileID)(nil)),
		"Profiles":               reflect.ValueOf((*pprofile.Profiles)(nil)),
		"ProfilesData":           reflect.ValueOf((*pprofile.ProfilesData)(nil)),
		"ProfilesDictionary":     reflect.ValueOf((*pprofile.ProfilesDictionary)(nil)),
		"ProfilesSlice":          reflect.ValueOf((*pprofile.ProfilesSlice)(nil)),
		"ProtoMarshaler":         reflect.ValueOf((*pprofile.ProtoMarshaler)(nil)),
		"ProtoUnmarshaler":       reflect.ValueOf((*pprofile.ProtoUnmarshaler)(nil)),
		"ResourceProfiles":       reflect.ValueOf((*pprofile.ResourceProfiles)(nil)),
		"ResourceProfilesSlice":  reflect.ValueOf((*pprofile.ResourceProfilesSlice)(nil)),
		"Sample":                 reflect.ValueOf((*pprofile.Sample)(nil)),
		"SampleSlice":            reflect.ValueOf((*pprofile.SampleSlice)(nil)),
		"ScopeProfiles":          reflect.ValueOf((*pprofile.ScopeProfiles)(nil)),
		"ScopeProfilesSlice":     reflect.ValueOf((*pprofile.ScopeProfilesSlice)(nil)),
		"Sizer":                  reflect.ValueOf((*pprofile.Sizer)(nil)),
		"Stack":                  reflect.ValueOf((*pprofile.Stack)(nil)),
		"StackSlice":             reflect.ValueOf((*pprofile.StackSlice)(nil)),
		"Unmarshaler":            reflect.ValueOf((*pprofile.Unmarshaler)(nil)),
		"ValueType":              reflect.ValueOf((*pprofile.ValueType)(nil)),
		"ValueTypeSlice":         reflect.ValueOf((*pprofile.ValueTypeSlice)(nil)),

		// interface wrapper definitions
		"_MarshalSizer": reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_pprofile_MarshalSizer)(nil)),
		"_Marshaler":    reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_pprofile_Marshaler)(nil)),
		"_Sizer":        reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_pprofile_Sizer)(nil)),
		"_Unmarshaler":  reflect.ValueOf((*_go_opentelemetry_io_collector_pdata_pprofile_Unmarshaler)(nil)),
	}
}

// _go_opentelemetry_io_collector_pdata_pprofile_MarshalSizer is an interface wrapper for MarshalSizer type
type _go_opentelemetry_io_collector_pdata_pprofile_MarshalSizer struct {
	IValue           interface{}
	WMarshalProfiles func(td pprofile.Profiles) ([]byte, error)
	WProfilesSize    func(td pprofile.Profiles) int
}

func (W _go_opentelemetry_io_collector_pdata_pprofile_MarshalSizer) MarshalProfiles(td pprofile.Profiles) ([]byte, error) {
	return W.WMarshalProfiles(td)
}
func (W _go_opentelemetry_io_collector_pdata_pprofile_MarshalSizer) ProfilesSize(td pprofile.Profiles) int {
	return W.WProfilesSize(td)
}

// _go_opentelemetry_io_collector_pdata_pprofile_Marshaler is an interface wrapper for Marshaler type
type _go_opentelemetry_io_collector_pdata_pprofile_Marshaler struct {
	IValue           interface{}
	WMarshalProfiles func(td pprofile.Profiles) ([]byte, error)
}

func (W _go_opentelemetry_io_collector_pdata_pprofile_Marshaler) MarshalProfiles(td pprofile.Profiles) ([]byte, error) {
	return W.WMarshalProfiles(td)
}

// _go_opentelemetry_io_collector_pdata_pprofile_Sizer is an interface wrapper for Sizer type
type _go_opentelemetry_io_collector_pdata_pprofile_Sizer struct {
	IValue        interface{}
	WProfilesSize func(td pprofile.Profiles) int
}

func (W _go_opentelemetry_io_collector_pdata_pprofile_Sizer) ProfilesSize(td pprofile.Profiles) int {
	return W.WProfilesSize(td)
}

// _go_opentelemetry_io_collector_pdata_pprofile_Unmarshaler is an interface wrapper for Unmarshaler type
type _go_opentelemetry_io_collector_pdata_pprofile_Unmarshaler struct {
	IValue             interface{}
	WUnmarshalProfiles func(buf []byte) (pprofile.Profiles, error)
}

func (W _go_opentelemetry_io_collector_pdata_pprofile_Unmarshaler) UnmarshalProfiles(buf []byte) (pprofile.Profiles, error) {
	return W.WUnmarshalProfiles(buf)
}
