// Code generated by 'yaegi extract go.opentelemetry.io/otel/trace'. DO NOT EDIT.

package capsule

import (
	"context"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/otel/trace/trace"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ContextWithRemoteSpanContext":    reflect.ValueOf(trace.ContextWithRemoteSpanContext),
		"ContextWithSpan":                 reflect.ValueOf(trace.ContextWithSpan),
		"ContextWithSpanContext":          reflect.ValueOf(trace.ContextWithSpanContext),
		"FlagsSampled":                    reflect.ValueOf(trace.FlagsSampled),
		"LinkFromContext":                 reflect.ValueOf(trace.LinkFromContext),
		"NewEventConfig":                  reflect.ValueOf(trace.NewEventConfig),
		"NewNoopTracerProvider":           reflect.ValueOf(trace.NewNoopTracerProvider),
		"NewSpanContext":                  reflect.ValueOf(trace.NewSpanContext),
		"NewSpanEndConfig":                reflect.ValueOf(trace.NewSpanEndConfig),
		"NewSpanStartConfig":              reflect.ValueOf(trace.NewSpanStartConfig),
		"NewTracerConfig":                 reflect.ValueOf(trace.NewTracerConfig),
		"ParseTraceState":                 reflect.ValueOf(trace.ParseTraceState),
		"SpanContextFromContext":          reflect.ValueOf(trace.SpanContextFromContext),
		"SpanFromContext":                 reflect.ValueOf(trace.SpanFromContext),
		"SpanIDFromHex":                   reflect.ValueOf(trace.SpanIDFromHex),
		"SpanKindClient":                  reflect.ValueOf(trace.SpanKindClient),
		"SpanKindConsumer":                reflect.ValueOf(trace.SpanKindConsumer),
		"SpanKindInternal":                reflect.ValueOf(trace.SpanKindInternal),
		"SpanKindProducer":                reflect.ValueOf(trace.SpanKindProducer),
		"SpanKindServer":                  reflect.ValueOf(trace.SpanKindServer),
		"SpanKindUnspecified":             reflect.ValueOf(trace.SpanKindUnspecified),
		"TraceIDFromHex":                  reflect.ValueOf(trace.TraceIDFromHex),
		"ValidateSpanKind":                reflect.ValueOf(trace.ValidateSpanKind),
		"WithAttributes":                  reflect.ValueOf(trace.WithAttributes),
		"WithInstrumentationAttributeSet": reflect.ValueOf(trace.WithInstrumentationAttributeSet),
		"WithInstrumentationAttributes":   reflect.ValueOf(trace.WithInstrumentationAttributes),
		"WithInstrumentationVersion":      reflect.ValueOf(trace.WithInstrumentationVersion),
		"WithLinks":                       reflect.ValueOf(trace.WithLinks),
		"WithNewRoot":                     reflect.ValueOf(trace.WithNewRoot),
		"WithSchemaURL":                   reflect.ValueOf(trace.WithSchemaURL),
		"WithSpanKind":                    reflect.ValueOf(trace.WithSpanKind),
		"WithStackTrace":                  reflect.ValueOf(trace.WithStackTrace),
		"WithTimestamp":                   reflect.ValueOf(trace.WithTimestamp),

		// type definitions
		"EventConfig":          reflect.ValueOf((*trace.EventConfig)(nil)),
		"EventOption":          reflect.ValueOf((*trace.EventOption)(nil)),
		"Link":                 reflect.ValueOf((*trace.Link)(nil)),
		"Span":                 reflect.ValueOf((*trace.Span)(nil)),
		"SpanConfig":           reflect.ValueOf((*trace.SpanConfig)(nil)),
		"SpanContext":          reflect.ValueOf((*trace.SpanContext)(nil)),
		"SpanContextConfig":    reflect.ValueOf((*trace.SpanContextConfig)(nil)),
		"SpanEndEventOption":   reflect.ValueOf((*trace.SpanEndEventOption)(nil)),
		"SpanEndOption":        reflect.ValueOf((*trace.SpanEndOption)(nil)),
		"SpanEventOption":      reflect.ValueOf((*trace.SpanEventOption)(nil)),
		"SpanID":               reflect.ValueOf((*trace.SpanID)(nil)),
		"SpanKind":             reflect.ValueOf((*trace.SpanKind)(nil)),
		"SpanOption":           reflect.ValueOf((*trace.SpanOption)(nil)),
		"SpanStartEventOption": reflect.ValueOf((*trace.SpanStartEventOption)(nil)),
		"SpanStartOption":      reflect.ValueOf((*trace.SpanStartOption)(nil)),
		"TraceFlags":           reflect.ValueOf((*trace.TraceFlags)(nil)),
		"TraceID":              reflect.ValueOf((*trace.TraceID)(nil)),
		"TraceState":           reflect.ValueOf((*trace.TraceState)(nil)),
		"Tracer":               reflect.ValueOf((*trace.Tracer)(nil)),
		"TracerConfig":         reflect.ValueOf((*trace.TracerConfig)(nil)),
		"TracerOption":         reflect.ValueOf((*trace.TracerOption)(nil)),
		"TracerProvider":       reflect.ValueOf((*trace.TracerProvider)(nil)),

		// interface wrapper definitions
		"_EventOption":          reflect.ValueOf((*_go_opentelemetry_io_otel_trace_EventOption)(nil)),
		"_Span":                 reflect.ValueOf((*_go_opentelemetry_io_otel_trace_Span)(nil)),
		"_SpanEndEventOption":   reflect.ValueOf((*_go_opentelemetry_io_otel_trace_SpanEndEventOption)(nil)),
		"_SpanEndOption":        reflect.ValueOf((*_go_opentelemetry_io_otel_trace_SpanEndOption)(nil)),
		"_SpanEventOption":      reflect.ValueOf((*_go_opentelemetry_io_otel_trace_SpanEventOption)(nil)),
		"_SpanOption":           reflect.ValueOf((*_go_opentelemetry_io_otel_trace_SpanOption)(nil)),
		"_SpanStartEventOption": reflect.ValueOf((*_go_opentelemetry_io_otel_trace_SpanStartEventOption)(nil)),
		"_SpanStartOption":      reflect.ValueOf((*_go_opentelemetry_io_otel_trace_SpanStartOption)(nil)),
		"_Tracer":               reflect.ValueOf((*_go_opentelemetry_io_otel_trace_Tracer)(nil)),
		"_TracerOption":         reflect.ValueOf((*_go_opentelemetry_io_otel_trace_TracerOption)(nil)),
		"_TracerProvider":       reflect.ValueOf((*_go_opentelemetry_io_otel_trace_TracerProvider)(nil)),
	}
}

// _go_opentelemetry_io_otel_trace_EventOption is an interface wrapper for EventOption type
type _go_opentelemetry_io_otel_trace_EventOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_trace_Span is an interface wrapper for Span type
type _go_opentelemetry_io_otel_trace_Span struct {
	IValue          interface{}
	WAddEvent       func(name string, options ...trace.EventOption)
	WAddLink        func(link trace.Link)
	WEnd            func(options ...trace.SpanEndOption)
	WIsRecording    func() bool
	WRecordError    func(err error, options ...trace.EventOption)
	WSetAttributes  func(kv ...attribute.KeyValue)
	WSetName        func(name string)
	WSetStatus      func(code codes.Code, description string)
	WSpanContext    func() trace.SpanContext
	WTracerProvider func() trace.TracerProvider
}

func (W _go_opentelemetry_io_otel_trace_Span) AddEvent(name string, options ...trace.EventOption) {
	W.WAddEvent(name, options...)
}
func (W _go_opentelemetry_io_otel_trace_Span) AddLink(link trace.Link)            { W.WAddLink(link) }
func (W _go_opentelemetry_io_otel_trace_Span) End(options ...trace.SpanEndOption) { W.WEnd(options...) }
func (W _go_opentelemetry_io_otel_trace_Span) IsRecording() bool                  { return W.WIsRecording() }
func (W _go_opentelemetry_io_otel_trace_Span) RecordError(err error, options ...trace.EventOption) {
	W.WRecordError(err, options...)
}
func (W _go_opentelemetry_io_otel_trace_Span) SetAttributes(kv ...attribute.KeyValue) {
	W.WSetAttributes(kv...)
}
func (W _go_opentelemetry_io_otel_trace_Span) SetName(name string) { W.WSetName(name) }
func (W _go_opentelemetry_io_otel_trace_Span) SetStatus(code codes.Code, description string) {
	W.WSetStatus(code, description)
}
func (W _go_opentelemetry_io_otel_trace_Span) SpanContext() trace.SpanContext {
	return W.WSpanContext()
}
func (W _go_opentelemetry_io_otel_trace_Span) TracerProvider() trace.TracerProvider {
	return W.WTracerProvider()
}

// _go_opentelemetry_io_otel_trace_SpanEndEventOption is an interface wrapper for SpanEndEventOption type
type _go_opentelemetry_io_otel_trace_SpanEndEventOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_trace_SpanEndOption is an interface wrapper for SpanEndOption type
type _go_opentelemetry_io_otel_trace_SpanEndOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_trace_SpanEventOption is an interface wrapper for SpanEventOption type
type _go_opentelemetry_io_otel_trace_SpanEventOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_trace_SpanOption is an interface wrapper for SpanOption type
type _go_opentelemetry_io_otel_trace_SpanOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_trace_SpanStartEventOption is an interface wrapper for SpanStartEventOption type
type _go_opentelemetry_io_otel_trace_SpanStartEventOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_trace_SpanStartOption is an interface wrapper for SpanStartOption type
type _go_opentelemetry_io_otel_trace_SpanStartOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_trace_Tracer is an interface wrapper for Tracer type
type _go_opentelemetry_io_otel_trace_Tracer struct {
	IValue interface{}
	WStart func(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span)
}

func (W _go_opentelemetry_io_otel_trace_Tracer) Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span) {
	return W.WStart(ctx, spanName, opts...)
}

// _go_opentelemetry_io_otel_trace_TracerOption is an interface wrapper for TracerOption type
type _go_opentelemetry_io_otel_trace_TracerOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_otel_trace_TracerProvider is an interface wrapper for TracerProvider type
type _go_opentelemetry_io_otel_trace_TracerProvider struct {
	IValue  interface{}
	WTracer func(name string, options ...trace.TracerOption) trace.Tracer
}

func (W _go_opentelemetry_io_otel_trace_TracerProvider) Tracer(name string, options ...trace.TracerOption) trace.Tracer {
	return W.WTracer(name, options...)
}
