// Code generated by 'yaegi extract go.opentelemetry.io/collector/consumer/xconsumer'. DO NOT EDIT.
// Modified: replaced consumer/internal.Capabilities with consumer.Capabilities.

package capsule

import (
	"context"
	"go.opentelemetry.io/collector/consumer"
	"go.opentelemetry.io/collector/consumer/xconsumer"
	"go.opentelemetry.io/collector/pdata/pprofile"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/consumer/xconsumer/xconsumer"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewProfiles": reflect.ValueOf(xconsumer.NewProfiles),

		// type definitions
		"ConsumeProfilesFunc": reflect.ValueOf((*xconsumer.ConsumeProfilesFunc)(nil)),
		"Profiles":            reflect.ValueOf((*xconsumer.Profiles)(nil)),

		// interface wrapper definitions
		"_Profiles": reflect.ValueOf((*_go_opentelemetry_io_collector_consumer_xconsumer_Profiles)(nil)),
	}
}

// _go_opentelemetry_io_collector_consumer_xconsumer_Profiles is an interface wrapper for Profiles type
type _go_opentelemetry_io_collector_consumer_xconsumer_Profiles struct {
	IValue           interface{}
	WCapabilities    func() consumer.Capabilities
	WConsumeProfiles func(ctx context.Context, td pprofile.Profiles) error
}

func (W _go_opentelemetry_io_collector_consumer_xconsumer_Profiles) Capabilities() consumer.Capabilities {
	return W.WCapabilities()
}
func (W _go_opentelemetry_io_collector_consumer_xconsumer_Profiles) ConsumeProfiles(ctx context.Context, td pprofile.Profiles) error {
	return W.WConsumeProfiles(ctx, td)
}
