// Code generated by 'yaegi extract go.opentelemetry.io/collector/exporter'. DO NOT EDIT.

package capsule

import (
	"context"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/consumer"
	"go.opentelemetry.io/collector/exporter"
	"go.opentelemetry.io/collector/pdata/plog"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/pdata/ptrace"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/exporter/exporter"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewFactory":  reflect.ValueOf(exporter.NewFactory),
		"WithLogs":    reflect.ValueOf(exporter.WithLogs),
		"WithMetrics": reflect.ValueOf(exporter.WithMetrics),
		"WithTraces":  reflect.ValueOf(exporter.WithTraces),

		// type definitions
		"CreateLogsFunc":    reflect.ValueOf((*exporter.CreateLogsFunc)(nil)),
		"CreateMetricsFunc": reflect.ValueOf((*exporter.CreateMetricsFunc)(nil)),
		"CreateTracesFunc":  reflect.ValueOf((*exporter.CreateTracesFunc)(nil)),
		"Factory":           reflect.ValueOf((*exporter.Factory)(nil)),
		"FactoryOption":     reflect.ValueOf((*exporter.FactoryOption)(nil)),
		"Logs":              reflect.ValueOf((*exporter.Logs)(nil)),
		"Metrics":           reflect.ValueOf((*exporter.Metrics)(nil)),
		"Settings":          reflect.ValueOf((*exporter.Settings)(nil)),
		"Traces":            reflect.ValueOf((*exporter.Traces)(nil)),

		// interface wrapper definitions
		"_Factory":       reflect.ValueOf((*_go_opentelemetry_io_collector_exporter_Factory)(nil)),
		"_FactoryOption": reflect.ValueOf((*_go_opentelemetry_io_collector_exporter_FactoryOption)(nil)),
		"_Logs":          reflect.ValueOf((*_go_opentelemetry_io_collector_exporter_Logs)(nil)),
		"_Metrics":       reflect.ValueOf((*_go_opentelemetry_io_collector_exporter_Metrics)(nil)),
		"_Traces":        reflect.ValueOf((*_go_opentelemetry_io_collector_exporter_Traces)(nil)),
	}
}

// _go_opentelemetry_io_collector_exporter_Factory is an interface wrapper for Factory type
type _go_opentelemetry_io_collector_exporter_Factory struct {
	IValue               interface{}
	WCreateDefaultConfig func() component.Config
	WCreateLogs          func(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Logs, error)
	WCreateMetrics       func(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Metrics, error)
	WCreateTraces        func(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Traces, error)
	WLogsStability       func() component.StabilityLevel
	WMetricsStability    func() component.StabilityLevel
	WTracesStability     func() component.StabilityLevel
	WType                func() component.Type
}

func (W _go_opentelemetry_io_collector_exporter_Factory) CreateDefaultConfig() component.Config {
	return W.WCreateDefaultConfig()
}
func (W _go_opentelemetry_io_collector_exporter_Factory) CreateLogs(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Logs, error) {
	return W.WCreateLogs(ctx, set, cfg)
}
func (W _go_opentelemetry_io_collector_exporter_Factory) CreateMetrics(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Metrics, error) {
	return W.WCreateMetrics(ctx, set, cfg)
}
func (W _go_opentelemetry_io_collector_exporter_Factory) CreateTraces(ctx context.Context, set exporter.Settings, cfg component.Config) (exporter.Traces, error) {
	return W.WCreateTraces(ctx, set, cfg)
}
func (W _go_opentelemetry_io_collector_exporter_Factory) LogsStability() component.StabilityLevel {
	return W.WLogsStability()
}
func (W _go_opentelemetry_io_collector_exporter_Factory) MetricsStability() component.StabilityLevel {
	return W.WMetricsStability()
}
func (W _go_opentelemetry_io_collector_exporter_Factory) TracesStability() component.StabilityLevel {
	return W.WTracesStability()
}
func (W _go_opentelemetry_io_collector_exporter_Factory) Type() component.Type { return W.WType() }

// _go_opentelemetry_io_collector_exporter_FactoryOption is an interface wrapper for FactoryOption type
type _go_opentelemetry_io_collector_exporter_FactoryOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_collector_exporter_Logs is an interface wrapper for Logs type
type _go_opentelemetry_io_collector_exporter_Logs struct {
	IValue        interface{}
	WCapabilities func() consumer.Capabilities
	WConsumeLogs  func(ctx context.Context, ld plog.Logs) error
	WShutdown     func(ctx context.Context) error
	WStart        func(ctx context.Context, host component.Host) error
}

func (W _go_opentelemetry_io_collector_exporter_Logs) Capabilities() consumer.Capabilities {
	return W.WCapabilities()
}
func (W _go_opentelemetry_io_collector_exporter_Logs) ConsumeLogs(ctx context.Context, ld plog.Logs) error {
	return W.WConsumeLogs(ctx, ld)
}
func (W _go_opentelemetry_io_collector_exporter_Logs) Shutdown(ctx context.Context) error {
	return W.WShutdown(ctx)
}
func (W _go_opentelemetry_io_collector_exporter_Logs) Start(ctx context.Context, host component.Host) error {
	return W.WStart(ctx, host)
}

// _go_opentelemetry_io_collector_exporter_Metrics is an interface wrapper for Metrics type
type _go_opentelemetry_io_collector_exporter_Metrics struct {
	IValue          interface{}
	WCapabilities   func() consumer.Capabilities
	WConsumeMetrics func(ctx context.Context, md pmetric.Metrics) error
	WShutdown       func(ctx context.Context) error
	WStart          func(ctx context.Context, host component.Host) error
}

func (W _go_opentelemetry_io_collector_exporter_Metrics) Capabilities() consumer.Capabilities {
	return W.WCapabilities()
}
func (W _go_opentelemetry_io_collector_exporter_Metrics) ConsumeMetrics(ctx context.Context, md pmetric.Metrics) error {
	return W.WConsumeMetrics(ctx, md)
}
func (W _go_opentelemetry_io_collector_exporter_Metrics) Shutdown(ctx context.Context) error {
	return W.WShutdown(ctx)
}
func (W _go_opentelemetry_io_collector_exporter_Metrics) Start(ctx context.Context, host component.Host) error {
	return W.WStart(ctx, host)
}

// _go_opentelemetry_io_collector_exporter_Traces is an interface wrapper for Traces type
type _go_opentelemetry_io_collector_exporter_Traces struct {
	IValue         interface{}
	WCapabilities  func() consumer.Capabilities
	WConsumeTraces func(ctx context.Context, td ptrace.Traces) error
	WShutdown      func(ctx context.Context) error
	WStart         func(ctx context.Context, host component.Host) error
}

func (W _go_opentelemetry_io_collector_exporter_Traces) Capabilities() consumer.Capabilities {
	return W.WCapabilities()
}
func (W _go_opentelemetry_io_collector_exporter_Traces) ConsumeTraces(ctx context.Context, td ptrace.Traces) error {
	return W.WConsumeTraces(ctx, td)
}
func (W _go_opentelemetry_io_collector_exporter_Traces) Shutdown(ctx context.Context) error {
	return W.WShutdown(ctx)
}
func (W _go_opentelemetry_io_collector_exporter_Traces) Start(ctx context.Context, host component.Host) error {
	return W.WStart(ctx, host)
}
