// Code generated by 'yaegi extract go.opentelemetry.io/collector/component/componentstatus'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/collector/component/componentstatus"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/collector/component/componentstatus/componentstatus"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewEvent":                 reflect.ValueOf(componentstatus.NewEvent),
		"NewFatalErrorEvent":       reflect.ValueOf(componentstatus.NewFatalErrorEvent),
		"NewInstanceID":            reflect.ValueOf(componentstatus.NewInstanceID),
		"NewPermanentErrorEvent":   reflect.ValueOf(componentstatus.NewPermanentErrorEvent),
		"NewRecoverableErrorEvent": reflect.ValueOf(componentstatus.NewRecoverableErrorEvent),
		"ReportStatus":             reflect.ValueOf(componentstatus.ReportStatus),
		"StatusFatalError":         reflect.ValueOf(componentstatus.StatusFatalError),
		"StatusIsError":            reflect.ValueOf(componentstatus.StatusIsError),
		"StatusNone":               reflect.ValueOf(componentstatus.StatusNone),
		"StatusOK":                 reflect.ValueOf(componentstatus.StatusOK),
		"StatusPermanentError":     reflect.ValueOf(componentstatus.StatusPermanentError),
		"StatusRecoverableError":   reflect.ValueOf(componentstatus.StatusRecoverableError),
		"StatusStarting":           reflect.ValueOf(componentstatus.StatusStarting),
		"StatusStopped":            reflect.ValueOf(componentstatus.StatusStopped),
		"StatusStopping":           reflect.ValueOf(componentstatus.StatusStopping),
		"WithAttributes":           reflect.ValueOf(componentstatus.WithAttributes),
		"WithError":                reflect.ValueOf(componentstatus.WithError),

		// type definitions
		"Event":              reflect.ValueOf((*componentstatus.Event)(nil)),
		"EventBuilderOption": reflect.ValueOf((*componentstatus.EventBuilderOption)(nil)),
		"InstanceID":         reflect.ValueOf((*componentstatus.InstanceID)(nil)),
		"Reporter":           reflect.ValueOf((*componentstatus.Reporter)(nil)),
		"Status":             reflect.ValueOf((*componentstatus.Status)(nil)),
		"Watcher":            reflect.ValueOf((*componentstatus.Watcher)(nil)),

		// interface wrapper definitions
		"_EventBuilderOption": reflect.ValueOf((*_go_opentelemetry_io_collector_component_componentstatus_EventBuilderOption)(nil)),
		"_Reporter":           reflect.ValueOf((*_go_opentelemetry_io_collector_component_componentstatus_Reporter)(nil)),
		"_Watcher":            reflect.ValueOf((*_go_opentelemetry_io_collector_component_componentstatus_Watcher)(nil)),
	}
}

// _go_opentelemetry_io_collector_component_componentstatus_EventBuilderOption is an interface wrapper for EventBuilderOption type
type _go_opentelemetry_io_collector_component_componentstatus_EventBuilderOption struct {
	IValue interface{}
}

// _go_opentelemetry_io_collector_component_componentstatus_Reporter is an interface wrapper for Reporter type
type _go_opentelemetry_io_collector_component_componentstatus_Reporter struct {
	IValue  interface{}
	WReport func(a0 *componentstatus.Event)
}

func (W _go_opentelemetry_io_collector_component_componentstatus_Reporter) Report(a0 *componentstatus.Event) {
	W.WReport(a0)
}

// _go_opentelemetry_io_collector_component_componentstatus_Watcher is an interface wrapper for Watcher type
type _go_opentelemetry_io_collector_component_componentstatus_Watcher struct {
	IValue                  interface{}
	WComponentStatusChanged func(source *componentstatus.InstanceID, event *componentstatus.Event)
}

func (W _go_opentelemetry_io_collector_component_componentstatus_Watcher) ComponentStatusChanged(source *componentstatus.InstanceID, event *componentstatus.Event) {
	W.WComponentStatusChanged(source, event)
}
