// Code generated by 'yaegi extract go.opentelemetry.io/otel/attribute'. DO NOT EDIT.

package capsule

import (
	"go.opentelemetry.io/otel/attribute"
	"reflect"
)

func init() {
	Symbols["go.opentelemetry.io/otel/attribute/attribute"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BOOL":                       reflect.ValueOf(attribute.BOOL),
		"BOOLSLICE":                  reflect.ValueOf(attribute.BOOLSLICE),
		"Bool":                       reflect.ValueOf(attribute.Bool),
		"BoolSlice":                  reflect.ValueOf(attribute.BoolSlice),
		"BoolSliceValue":             reflect.ValueOf(attribute.BoolSliceValue),
		"BoolValue":                  reflect.ValueOf(attribute.BoolValue),
		"DefaultEncoder":             reflect.ValueOf(attribute.DefaultEncoder),
		"EmptySet":                   reflect.ValueOf(attribute.EmptySet),
		"FLOAT64":                    reflect.ValueOf(attribute.FLOAT64),
		"FLOAT64SLICE":               reflect.ValueOf(attribute.FLOAT64SLICE),
		"Float64":                    reflect.ValueOf(attribute.Float64),
		"Float64Slice":               reflect.ValueOf(attribute.Float64Slice),
		"Float64SliceValue":          reflect.ValueOf(attribute.Float64SliceValue),
		"Float64Value":               reflect.ValueOf(attribute.Float64Value),
		"INT64":                      reflect.ValueOf(attribute.INT64),
		"INT64SLICE":                 reflect.ValueOf(attribute.INT64SLICE),
		"INVALID":                    reflect.ValueOf(attribute.INVALID),
		"Int":                        reflect.ValueOf(attribute.Int),
		"Int64":                      reflect.ValueOf(attribute.Int64),
		"Int64Slice":                 reflect.ValueOf(attribute.Int64Slice),
		"Int64SliceValue":            reflect.ValueOf(attribute.Int64SliceValue),
		"Int64Value":                 reflect.ValueOf(attribute.Int64Value),
		"IntSlice":                   reflect.ValueOf(attribute.IntSlice),
		"IntSliceValue":              reflect.ValueOf(attribute.IntSliceValue),
		"IntValue":                   reflect.ValueOf(attribute.IntValue),
		"NewAllowKeysFilter":         reflect.ValueOf(attribute.NewAllowKeysFilter),
		"NewDenyKeysFilter":          reflect.ValueOf(attribute.NewDenyKeysFilter),
		"NewEncoderID":               reflect.ValueOf(attribute.NewEncoderID),
		"NewMergeIterator":           reflect.ValueOf(attribute.NewMergeIterator),
		"NewSet":                     reflect.ValueOf(attribute.NewSet),
		"NewSetWithFiltered":         reflect.ValueOf(attribute.NewSetWithFiltered),
		"NewSetWithSortable":         reflect.ValueOf(attribute.NewSetWithSortable),
		"NewSetWithSortableFiltered": reflect.ValueOf(attribute.NewSetWithSortableFiltered),
		"STRING":                     reflect.ValueOf(attribute.STRING),
		"STRINGSLICE":                reflect.ValueOf(attribute.STRINGSLICE),
		"String":                     reflect.ValueOf(attribute.String),
		"StringSlice":                reflect.ValueOf(attribute.StringSlice),
		"StringSliceValue":           reflect.ValueOf(attribute.StringSliceValue),
		"StringValue":                reflect.ValueOf(attribute.StringValue),
		"Stringer":                   reflect.ValueOf(attribute.Stringer),

		// type definitions
		"Distinct":      reflect.ValueOf((*attribute.Distinct)(nil)),
		"Encoder":       reflect.ValueOf((*attribute.Encoder)(nil)),
		"EncoderID":     reflect.ValueOf((*attribute.EncoderID)(nil)),
		"Filter":        reflect.ValueOf((*attribute.Filter)(nil)),
		"Iterator":      reflect.ValueOf((*attribute.Iterator)(nil)),
		"Key":           reflect.ValueOf((*attribute.Key)(nil)),
		"KeyValue":      reflect.ValueOf((*attribute.KeyValue)(nil)),
		"MergeIterator": reflect.ValueOf((*attribute.MergeIterator)(nil)),
		"Set":           reflect.ValueOf((*attribute.Set)(nil)),
		"Sortable":      reflect.ValueOf((*attribute.Sortable)(nil)),
		"Type":          reflect.ValueOf((*attribute.Type)(nil)),
		"Value":         reflect.ValueOf((*attribute.Value)(nil)),

		// interface wrapper definitions
		"_Encoder": reflect.ValueOf((*_go_opentelemetry_io_otel_attribute_Encoder)(nil)),
	}
}

// _go_opentelemetry_io_otel_attribute_Encoder is an interface wrapper for Encoder type
type _go_opentelemetry_io_otel_attribute_Encoder struct {
	IValue  interface{}
	WEncode func(iterator attribute.Iterator) string
	WID     func() attribute.EncoderID
}

func (W _go_opentelemetry_io_otel_attribute_Encoder) Encode(iterator attribute.Iterator) string {
	return W.WEncode(iterator)
}
func (W _go_opentelemetry_io_otel_attribute_Encoder) ID() attribute.EncoderID { return W.WID() }
