// Code generated by 'yaegi extract go.uber.org/zap'. DO NOT EDIT.

package capsule

import (
	"go.uber.org/zap"
	"reflect"
)

func init() {
	Symbols["go.uber.org/zap/zap"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddCaller":                   reflect.ValueOf(zap.AddCaller),
		"AddCallerSkip":               reflect.ValueOf(zap.AddCallerSkip),
		"AddStacktrace":               reflect.ValueOf(zap.AddStacktrace),
		"Any":                         reflect.ValueOf(zap.Any),
		"Array":                       reflect.ValueOf(zap.Array),
		"Binary":                      reflect.ValueOf(zap.Binary),
		"Bool":                        reflect.ValueOf(zap.Bool),
		"Boolp":                       reflect.ValueOf(zap.Boolp),
		"Bools":                       reflect.ValueOf(zap.Bools),
		"ByteString":                  reflect.ValueOf(zap.ByteString),
		"ByteStrings":                 reflect.ValueOf(zap.ByteStrings),
		"CombineWriteSyncers":         reflect.ValueOf(zap.CombineWriteSyncers),
		"Complex128":                  reflect.ValueOf(zap.Complex128),
		"Complex128p":                 reflect.ValueOf(zap.Complex128p),
		"Complex128s":                 reflect.ValueOf(zap.Complex128s),
		"Complex64":                   reflect.ValueOf(zap.Complex64),
		"Complex64p":                  reflect.ValueOf(zap.Complex64p),
		"Complex64s":                  reflect.ValueOf(zap.Complex64s),
		"DPanicLevel":                 reflect.ValueOf(zap.DPanicLevel),
		"DebugLevel":                  reflect.ValueOf(zap.DebugLevel),
		"Development":                 reflect.ValueOf(zap.Development),
		"Dict":                        reflect.ValueOf(zap.Dict),
		"DictObject":                  reflect.ValueOf(zap.DictObject),
		"Duration":                    reflect.ValueOf(zap.Duration),
		"Durationp":                   reflect.ValueOf(zap.Durationp),
		"Durations":                   reflect.ValueOf(zap.Durations),
		"Error":                       reflect.ValueOf(zap.Error),
		"ErrorLevel":                  reflect.ValueOf(zap.ErrorLevel),
		"ErrorOutput":                 reflect.ValueOf(zap.ErrorOutput),
		"Errors":                      reflect.ValueOf(zap.Errors),
		"FatalLevel":                  reflect.ValueOf(zap.FatalLevel),
		"Fields":                      reflect.ValueOf(zap.Fields),
		"Float32":                     reflect.ValueOf(zap.Float32),
		"Float32p":                    reflect.ValueOf(zap.Float32p),
		"Float32s":                    reflect.ValueOf(zap.Float32s),
		"Float64":                     reflect.ValueOf(zap.Float64),
		"Float64p":                    reflect.ValueOf(zap.Float64p),
		"Float64s":                    reflect.ValueOf(zap.Float64s),
		"Hooks":                       reflect.ValueOf(zap.Hooks),
		"IncreaseLevel":               reflect.ValueOf(zap.IncreaseLevel),
		"InfoLevel":                   reflect.ValueOf(zap.InfoLevel),
		"Inline":                      reflect.ValueOf(zap.Inline),
		"Int":                         reflect.ValueOf(zap.Int),
		"Int16":                       reflect.ValueOf(zap.Int16),
		"Int16p":                      reflect.ValueOf(zap.Int16p),
		"Int16s":                      reflect.ValueOf(zap.Int16s),
		"Int32":                       reflect.ValueOf(zap.Int32),
		"Int32p":                      reflect.ValueOf(zap.Int32p),
		"Int32s":                      reflect.ValueOf(zap.Int32s),
		"Int64":                       reflect.ValueOf(zap.Int64),
		"Int64p":                      reflect.ValueOf(zap.Int64p),
		"Int64s":                      reflect.ValueOf(zap.Int64s),
		"Int8":                        reflect.ValueOf(zap.Int8),
		"Int8p":                       reflect.ValueOf(zap.Int8p),
		"Int8s":                       reflect.ValueOf(zap.Int8s),
		"Intp":                        reflect.ValueOf(zap.Intp),
		"Ints":                        reflect.ValueOf(zap.Ints),
		"L":                           reflect.ValueOf(zap.L),
		"LevelFlag":                   reflect.ValueOf(zap.LevelFlag),
		"Must":                        reflect.ValueOf(zap.Must),
		"NamedError":                  reflect.ValueOf(zap.NamedError),
		"Namespace":                   reflect.ValueOf(zap.Namespace),
		"New":                         reflect.ValueOf(zap.New),
		"NewAtomicLevel":              reflect.ValueOf(zap.NewAtomicLevel),
		"NewAtomicLevelAt":            reflect.ValueOf(zap.NewAtomicLevelAt),
		"NewDevelopment":              reflect.ValueOf(zap.NewDevelopment),
		"NewDevelopmentConfig":        reflect.ValueOf(zap.NewDevelopmentConfig),
		"NewDevelopmentEncoderConfig": reflect.ValueOf(zap.NewDevelopmentEncoderConfig),
		"NewExample":                  reflect.ValueOf(zap.NewExample),
		"NewNop":                      reflect.ValueOf(zap.NewNop),
		"NewProduction":               reflect.ValueOf(zap.NewProduction),
		"NewProductionConfig":         reflect.ValueOf(zap.NewProductionConfig),
		"NewProductionEncoderConfig":  reflect.ValueOf(zap.NewProductionEncoderConfig),
		"NewStdLog":                   reflect.ValueOf(zap.NewStdLog),
		"NewStdLogAt":                 reflect.ValueOf(zap.NewStdLogAt),
		"Object":                      reflect.ValueOf(zap.Object),
		"OnFatal":                     reflect.ValueOf(zap.OnFatal),
		"Open":                        reflect.ValueOf(zap.Open),
		"PanicLevel":                  reflect.ValueOf(zap.PanicLevel),
		"ParseAtomicLevel":            reflect.ValueOf(zap.ParseAtomicLevel),
		"RedirectStdLog":              reflect.ValueOf(zap.RedirectStdLog),
		"RedirectStdLogAt":            reflect.ValueOf(zap.RedirectStdLogAt),
		"Reflect":                     reflect.ValueOf(zap.Reflect),
		"RegisterEncoder":             reflect.ValueOf(zap.RegisterEncoder),
		"RegisterSink":                reflect.ValueOf(zap.RegisterSink),
		"ReplaceGlobals":              reflect.ValueOf(zap.ReplaceGlobals),
		"S":                           reflect.ValueOf(zap.S),
		"Skip":                        reflect.ValueOf(zap.Skip),
		"Stack":                       reflect.ValueOf(zap.Stack),
		"StackSkip":                   reflect.ValueOf(zap.StackSkip),
		"String":                      reflect.ValueOf(zap.String),
		"Stringer":                    reflect.ValueOf(zap.Stringer),
		"Stringp":                     reflect.ValueOf(zap.Stringp),
		"Strings":                     reflect.ValueOf(zap.Strings),
		"Time":                        reflect.ValueOf(zap.Time),
		"Timep":                       reflect.ValueOf(zap.Timep),
		"Times":                       reflect.ValueOf(zap.Times),
		"Uint":                        reflect.ValueOf(zap.Uint),
		"Uint16":                      reflect.ValueOf(zap.Uint16),
		"Uint16p":                     reflect.ValueOf(zap.Uint16p),
		"Uint16s":                     reflect.ValueOf(zap.Uint16s),
		"Uint32":                      reflect.ValueOf(zap.Uint32),
		"Uint32p":                     reflect.ValueOf(zap.Uint32p),
		"Uint32s":                     reflect.ValueOf(zap.Uint32s),
		"Uint64":                      reflect.ValueOf(zap.Uint64),
		"Uint64p":                     reflect.ValueOf(zap.Uint64p),
		"Uint64s":                     reflect.ValueOf(zap.Uint64s),
		"Uint8":                       reflect.ValueOf(zap.Uint8),
		"Uint8p":                      reflect.ValueOf(zap.Uint8p),
		"Uint8s":                      reflect.ValueOf(zap.Uint8s),
		"Uintp":                       reflect.ValueOf(zap.Uintp),
		"Uintptr":                     reflect.ValueOf(zap.Uintptr),
		"Uintptrp":                    reflect.ValueOf(zap.Uintptrp),
		"Uintptrs":                    reflect.ValueOf(zap.Uintptrs),
		"Uints":                       reflect.ValueOf(zap.Uints),
		"WarnLevel":                   reflect.ValueOf(zap.WarnLevel),
		"WithCaller":                  reflect.ValueOf(zap.WithCaller),
		"WithClock":                   reflect.ValueOf(zap.WithClock),
		"WithFatalHook":               reflect.ValueOf(zap.WithFatalHook),
		"WithPanicHook":               reflect.ValueOf(zap.WithPanicHook),
		"WrapCore":                    reflect.ValueOf(zap.WrapCore),

		// type definitions
		"AtomicLevel":      reflect.ValueOf((*zap.AtomicLevel)(nil)),
		"Config":           reflect.ValueOf((*zap.Config)(nil)),
		"Field":            reflect.ValueOf((*zap.Field)(nil)),
		"LevelEnablerFunc": reflect.ValueOf((*zap.LevelEnablerFunc)(nil)),
		"Logger":           reflect.ValueOf((*zap.Logger)(nil)),
		"Option":           reflect.ValueOf((*zap.Option)(nil)),
		"SamplingConfig":   reflect.ValueOf((*zap.SamplingConfig)(nil)),
		"Sink":             reflect.ValueOf((*zap.Sink)(nil)),
		"SugaredLogger":    reflect.ValueOf((*zap.SugaredLogger)(nil)),

		// interface wrapper definitions
		"_Option": reflect.ValueOf((*_go_uber_org_zap_Option)(nil)),
		"_Sink":   reflect.ValueOf((*_go_uber_org_zap_Sink)(nil)),
	}
}

// _go_uber_org_zap_Option is an interface wrapper for Option type
type _go_uber_org_zap_Option struct {
	IValue interface{}
}

// _go_uber_org_zap_Sink is an interface wrapper for Sink type
type _go_uber_org_zap_Sink struct {
	IValue interface{}
	WClose func() error
	WSync  func() error
	WWrite func(p []byte) (n int, err error)
}

func (W _go_uber_org_zap_Sink) Close() error                      { return W.WClose() }
func (W _go_uber_org_zap_Sink) Sync() error                       { return W.WSync() }
func (W _go_uber_org_zap_Sink) Write(p []byte) (n int, err error) { return W.WWrite(p) }
