// Code generated by 'yaegi extract go.uber.org/multierr'. DO NOT EDIT.

package capsule

import (
	"go.uber.org/multierr"
	"reflect"
)

func init() {
	Symbols["go.uber.org/multierr/multierr"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Append":       reflect.ValueOf(multierr.Append),
		"AppendFunc":   reflect.ValueOf(multierr.AppendFunc),
		"AppendInto":   reflect.ValueOf(multierr.AppendInto),
		"AppendInvoke": reflect.ValueOf(multierr.AppendInvoke),
		"Close":        reflect.ValueOf(multierr.Close),
		"Combine":      reflect.ValueOf(multierr.Combine),
		"Errors":       reflect.ValueOf(multierr.Errors),
		"Every":        reflect.ValueOf(multierr.Every),

		// type definitions
		"Invoke":  reflect.ValueOf((*multierr.Invoke)(nil)),
		"Invoker": reflect.ValueOf((*multierr.Invoker)(nil)),

		// interface wrapper definitions
		"_Invoker": reflect.ValueOf((*_go_uber_org_multierr_Invoker)(nil)),
	}
}

// _go_uber_org_multierr_Invoker is an interface wrapper for Invoker type
type _go_uber_org_multierr_Invoker struct {
	IValue  interface{}
	WInvoke func() error
}

func (W _go_uber_org_multierr_Invoker) Invoke() error { return W.WInvoke() }
