// Code generated by 'yaegi extract google.golang.org/grpc/credentials'. DO NOT EDIT.

package capsule

import (
	"context"
	"google.golang.org/grpc/credentials"
	"net"
	"reflect"
)

func init() {
	Symbols["google.golang.org/grpc/credentials/credentials"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CheckSecurityLevel":             reflect.ValueOf(credentials.CheckSecurityLevel),
		"ClientHandshakeInfoFromContext": reflect.ValueOf(credentials.ClientHandshakeInfoFromContext),
		"ErrConnDispatched":              reflect.ValueOf(&credentials.ErrConnDispatched).Elem(),
		"IntegrityOnly":                  reflect.ValueOf(credentials.IntegrityOnly),
		"InvalidSecurityLevel":           reflect.ValueOf(credentials.InvalidSecurityLevel),
		"NewClientTLSFromCert":           reflect.ValueOf(credentials.NewClientTLSFromCert),
		"NewClientTLSFromFile":           reflect.ValueOf(credentials.NewClientTLSFromFile),
		"NewContextWithRequestInfo":      reflect.ValueOf(credentials.NewContextWithRequestInfo),
		"NewServerTLSFromCert":           reflect.ValueOf(credentials.NewServerTLSFromCert),
		"NewServerTLSFromFile":           reflect.ValueOf(credentials.NewServerTLSFromFile),
		"NewTLS":                         reflect.ValueOf(credentials.NewTLS),
		"NoSecurity":                     reflect.ValueOf(credentials.NoSecurity),
		"PrivacyAndIntegrity":            reflect.ValueOf(credentials.PrivacyAndIntegrity),
		"RequestInfoFromContext":         reflect.ValueOf(credentials.RequestInfoFromContext),

		// type definitions
		"AuthInfo":                   reflect.ValueOf((*credentials.AuthInfo)(nil)),
		"AuthorityValidator":         reflect.ValueOf((*credentials.AuthorityValidator)(nil)),
		"Bundle":                     reflect.ValueOf((*credentials.Bundle)(nil)),
		"ChannelzSecurityInfo":       reflect.ValueOf((*credentials.ChannelzSecurityInfo)(nil)),
		"ChannelzSecurityValue":      reflect.ValueOf((*credentials.ChannelzSecurityValue)(nil)),
		"ClientHandshakeInfo":        reflect.ValueOf((*credentials.ClientHandshakeInfo)(nil)),
		"CommonAuthInfo":             reflect.ValueOf((*credentials.CommonAuthInfo)(nil)),
		"OtherChannelzSecurityValue": reflect.ValueOf((*credentials.OtherChannelzSecurityValue)(nil)),
		"PerRPCCredentials":          reflect.ValueOf((*credentials.PerRPCCredentials)(nil)),
		"ProtocolInfo":               reflect.ValueOf((*credentials.ProtocolInfo)(nil)),
		"RequestInfo":                reflect.ValueOf((*credentials.RequestInfo)(nil)),
		"SecurityLevel":              reflect.ValueOf((*credentials.SecurityLevel)(nil)),
		"TLSChannelzSecurityValue":   reflect.ValueOf((*credentials.TLSChannelzSecurityValue)(nil)),
		"TLSInfo":                    reflect.ValueOf((*credentials.TLSInfo)(nil)),
		"TransportCredentials":       reflect.ValueOf((*credentials.TransportCredentials)(nil)),

		// interface wrapper definitions
		"_AuthInfo":              reflect.ValueOf((*_google_golang_org_grpc_credentials_AuthInfo)(nil)),
		"_AuthorityValidator":    reflect.ValueOf((*_google_golang_org_grpc_credentials_AuthorityValidator)(nil)),
		"_Bundle":                reflect.ValueOf((*_google_golang_org_grpc_credentials_Bundle)(nil)),
		"_ChannelzSecurityInfo":  reflect.ValueOf((*_google_golang_org_grpc_credentials_ChannelzSecurityInfo)(nil)),
		"_ChannelzSecurityValue": reflect.ValueOf((*_google_golang_org_grpc_credentials_ChannelzSecurityValue)(nil)),
		"_PerRPCCredentials":     reflect.ValueOf((*_google_golang_org_grpc_credentials_PerRPCCredentials)(nil)),
		"_TransportCredentials":  reflect.ValueOf((*_google_golang_org_grpc_credentials_TransportCredentials)(nil)),
	}
}

// _google_golang_org_grpc_credentials_AuthInfo is an interface wrapper for AuthInfo type
type _google_golang_org_grpc_credentials_AuthInfo struct {
	IValue    interface{}
	WAuthType func() string
}

func (W _google_golang_org_grpc_credentials_AuthInfo) AuthType() string { return W.WAuthType() }

// _google_golang_org_grpc_credentials_AuthorityValidator is an interface wrapper for AuthorityValidator type
type _google_golang_org_grpc_credentials_AuthorityValidator struct {
	IValue             interface{}
	WValidateAuthority func(authority string) error
}

func (W _google_golang_org_grpc_credentials_AuthorityValidator) ValidateAuthority(authority string) error {
	return W.WValidateAuthority(authority)
}

// _google_golang_org_grpc_credentials_Bundle is an interface wrapper for Bundle type
type _google_golang_org_grpc_credentials_Bundle struct {
	IValue                interface{}
	WNewWithMode          func(mode string) (credentials.Bundle, error)
	WPerRPCCredentials    func() credentials.PerRPCCredentials
	WTransportCredentials func() credentials.TransportCredentials
}

func (W _google_golang_org_grpc_credentials_Bundle) NewWithMode(mode string) (credentials.Bundle, error) {
	return W.WNewWithMode(mode)
}
func (W _google_golang_org_grpc_credentials_Bundle) PerRPCCredentials() credentials.PerRPCCredentials {
	return W.WPerRPCCredentials()
}
func (W _google_golang_org_grpc_credentials_Bundle) TransportCredentials() credentials.TransportCredentials {
	return W.WTransportCredentials()
}

// _google_golang_org_grpc_credentials_ChannelzSecurityInfo is an interface wrapper for ChannelzSecurityInfo type
type _google_golang_org_grpc_credentials_ChannelzSecurityInfo struct {
	IValue            interface{}
	WGetSecurityValue func() credentials.ChannelzSecurityValue
}

func (W _google_golang_org_grpc_credentials_ChannelzSecurityInfo) GetSecurityValue() credentials.ChannelzSecurityValue {
	return W.WGetSecurityValue()
}

// _google_golang_org_grpc_credentials_ChannelzSecurityValue is an interface wrapper for ChannelzSecurityValue type
type _google_golang_org_grpc_credentials_ChannelzSecurityValue struct {
	IValue interface{}
}

// _google_golang_org_grpc_credentials_PerRPCCredentials is an interface wrapper for PerRPCCredentials type
type _google_golang_org_grpc_credentials_PerRPCCredentials struct {
	IValue                    interface{}
	WGetRequestMetadata       func(ctx context.Context, uri ...string) (map[string]string, error)
	WRequireTransportSecurity func() bool
}

func (W _google_golang_org_grpc_credentials_PerRPCCredentials) GetRequestMetadata(ctx context.Context, uri ...string) (map[string]string, error) {
	return W.WGetRequestMetadata(ctx, uri...)
}
func (W _google_golang_org_grpc_credentials_PerRPCCredentials) RequireTransportSecurity() bool {
	return W.WRequireTransportSecurity()
}

// _google_golang_org_grpc_credentials_TransportCredentials is an interface wrapper for TransportCredentials type
type _google_golang_org_grpc_credentials_TransportCredentials struct {
	IValue              interface{}
	WClientHandshake    func(a0 context.Context, a1 string, a2 net.Conn) (net.Conn, credentials.AuthInfo, error)
	WClone              func() credentials.TransportCredentials
	WInfo               func() credentials.ProtocolInfo
	WOverrideServerName func(a0 string) error
	WServerHandshake    func(a0 net.Conn) (net.Conn, credentials.AuthInfo, error)
}

func (W _google_golang_org_grpc_credentials_TransportCredentials) ClientHandshake(a0 context.Context, a1 string, a2 net.Conn) (net.Conn, credentials.AuthInfo, error) {
	return W.WClientHandshake(a0, a1, a2)
}
func (W _google_golang_org_grpc_credentials_TransportCredentials) Clone() credentials.TransportCredentials {
	return W.WClone()
}
func (W _google_golang_org_grpc_credentials_TransportCredentials) Info() credentials.ProtocolInfo {
	return W.WInfo()
}
func (W _google_golang_org_grpc_credentials_TransportCredentials) OverrideServerName(a0 string) error {
	return W.WOverrideServerName(a0)
}
func (W _google_golang_org_grpc_credentials_TransportCredentials) ServerHandshake(a0 net.Conn) (net.Conn, credentials.AuthInfo, error) {
	return W.WServerHandshake(a0)
}
