// Code generated by 'yaegi extract google.golang.org/grpc/status'. DO NOT EDIT.

package capsule

import (
	"google.golang.org/grpc/status"
	"reflect"
)

func init() {
	Symbols["google.golang.org/grpc/status/status"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Code":             reflect.ValueOf(status.Code),
		"Convert":          reflect.ValueOf(status.Convert),
		"Error":            reflect.ValueOf(status.Error),
		"ErrorProto":       reflect.ValueOf(status.ErrorProto),
		"Errorf":           reflect.ValueOf(status.Errorf),
		"FromContextError": reflect.ValueOf(status.FromContextError),
		"FromError":        reflect.ValueOf(status.FromError),
		"FromProto":        reflect.ValueOf(status.FromProto),
		"New":              reflect.ValueOf(status.New),
		"Newf":             reflect.ValueOf(status.Newf),

		// type definitions
		"Status": reflect.ValueOf((*status.Status)(nil)),
	}
}
