// Code generated by 'yaegi extract google.golang.org/grpc/grpclog'. DO NOT EDIT.

package capsule

import (
	"google.golang.org/grpc/grpclog"
	"reflect"
)

func init() {
	Symbols["google.golang.org/grpc/grpclog/grpclog"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Component":              reflect.ValueOf(grpclog.Component),
		"Error":                  reflect.ValueOf(grpclog.Error),
		"ErrorDepth":             reflect.ValueOf(grpclog.ErrorDepth),
		"Errorf":                 reflect.ValueOf(grpclog.Errorf),
		"Errorln":                reflect.ValueOf(grpclog.Errorln),
		"Fatal":                  reflect.ValueOf(grpclog.Fatal),
		"FatalDepth":             reflect.ValueOf(grpclog.FatalDepth),
		"Fatalf":                 reflect.ValueOf(grpclog.Fatalf),
		"Fatalln":                reflect.ValueOf(grpclog.Fatalln),
		"Info":                   reflect.ValueOf(grpclog.Info),
		"InfoDepth":              reflect.ValueOf(grpclog.InfoDepth),
		"Infof":                  reflect.ValueOf(grpclog.Infof),
		"Infoln":                 reflect.ValueOf(grpclog.Infoln),
		"NewLoggerV2":            reflect.ValueOf(grpclog.NewLoggerV2),
		"NewLoggerV2WithVerbosity": reflect.ValueOf(grpclog.NewLoggerV2WithVerbosity),
		"Print":                  reflect.ValueOf(grpclog.Print),
		"Printf":                 reflect.ValueOf(grpclog.Printf),
		"Println":                reflect.ValueOf(grpclog.Println),
		"SetLogger":              reflect.ValueOf(grpclog.SetLogger),
		"SetLoggerV2":            reflect.ValueOf(grpclog.SetLoggerV2),
		"V":                      reflect.ValueOf(grpclog.V),
		"Warning":                reflect.ValueOf(grpclog.Warning),
		"WarningDepth":           reflect.ValueOf(grpclog.WarningDepth),
		"Warningf":               reflect.ValueOf(grpclog.Warningf),
		"Warningln":              reflect.ValueOf(grpclog.Warningln),

		// type definitions
		"DepthLoggerV2": reflect.ValueOf((*grpclog.DepthLoggerV2)(nil)),
		"Logger":        reflect.ValueOf((*grpclog.Logger)(nil)),
		"LoggerV2":      reflect.ValueOf((*grpclog.LoggerV2)(nil)),

		// interface wrapper definitions
		"_DepthLoggerV2": reflect.ValueOf((*_google_golang_org_grpc_grpclog_DepthLoggerV2)(nil)),
		"_Logger":        reflect.ValueOf((*_google_golang_org_grpc_grpclog_Logger)(nil)),
		"_LoggerV2":      reflect.ValueOf((*_google_golang_org_grpc_grpclog_LoggerV2)(nil)),
	}
}

// _google_golang_org_grpc_grpclog_DepthLoggerV2 is an interface wrapper for DepthLoggerV2 type
type _google_golang_org_grpc_grpclog_DepthLoggerV2 struct {
	IValue       interface{}
	WError       func(args ...any)
	WErrorDepth  func(depth int, args ...any)
	WErrorf      func(format string, args ...any)
	WErrorln     func(args ...any)
	WFatal       func(args ...any)
	WFatalDepth  func(depth int, args ...any)
	WFatalf      func(format string, args ...any)
	WFatalln     func(args ...any)
	WInfo        func(args ...any)
	WInfoDepth   func(depth int, args ...any)
	WInfof       func(format string, args ...any)
	WInfoln      func(args ...any)
	WV           func(l int) bool
	WWarning     func(args ...any)
	WWarningDepth func(depth int, args ...any)
	WWarningf    func(format string, args ...any)
	WWarningln   func(args ...any)
}

func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Error(args ...any)                  { W.WError(args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) ErrorDepth(depth int, args ...any)   { W.WErrorDepth(depth, args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Errorf(format string, args ...any)   { W.WErrorf(format, args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Errorln(args ...any)                 { W.WErrorln(args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Fatal(args ...any)                   { W.WFatal(args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) FatalDepth(depth int, args ...any)   { W.WFatalDepth(depth, args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Fatalf(format string, args ...any)   { W.WFatalf(format, args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Fatalln(args ...any)                 { W.WFatalln(args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Info(args ...any)                    { W.WInfo(args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) InfoDepth(depth int, args ...any)    { W.WInfoDepth(depth, args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Infof(format string, args ...any)    { W.WInfof(format, args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Infoln(args ...any)                  { W.WInfoln(args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) V(l int) bool                       { return W.WV(l) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Warning(args ...any)                 { W.WWarning(args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) WarningDepth(depth int, args ...any) { W.WWarningDepth(depth, args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Warningf(format string, args ...any) { W.WWarningf(format, args...) }
func (W _google_golang_org_grpc_grpclog_DepthLoggerV2) Warningln(args ...any)               { W.WWarningln(args...) }

// _google_golang_org_grpc_grpclog_Logger is an interface wrapper for Logger type
type _google_golang_org_grpc_grpclog_Logger struct {
	IValue  interface{}
	WFatal  func(args ...any)
	WFatalf func(format string, args ...any)
	WFatalln func(args ...any)
	WPrint  func(args ...any)
	WPrintf func(format string, args ...any)
	WPrintln func(args ...any)
}

func (W _google_golang_org_grpc_grpclog_Logger) Fatal(args ...any)                { W.WFatal(args...) }
func (W _google_golang_org_grpc_grpclog_Logger) Fatalf(format string, args ...any) { W.WFatalf(format, args...) }
func (W _google_golang_org_grpc_grpclog_Logger) Fatalln(args ...any)               { W.WFatalln(args...) }
func (W _google_golang_org_grpc_grpclog_Logger) Print(args ...any)                 { W.WPrint(args...) }
func (W _google_golang_org_grpc_grpclog_Logger) Printf(format string, args ...any) { W.WPrintf(format, args...) }
func (W _google_golang_org_grpc_grpclog_Logger) Println(args ...any)               { W.WPrintln(args...) }

// _google_golang_org_grpc_grpclog_LoggerV2 is an interface wrapper for LoggerV2 type
type _google_golang_org_grpc_grpclog_LoggerV2 struct {
	IValue   interface{}
	WError   func(args ...any)
	WErrorf  func(format string, args ...any)
	WErrorln func(args ...any)
	WFatal   func(args ...any)
	WFatalf  func(format string, args ...any)
	WFatalln func(args ...any)
	WInfo    func(args ...any)
	WInfof   func(format string, args ...any)
	WInfoln  func(args ...any)
	WV       func(l int) bool
	WWarning func(args ...any)
	WWarningf func(format string, args ...any)
	WWarningln func(args ...any)
}

func (W _google_golang_org_grpc_grpclog_LoggerV2) Error(args ...any)                  { W.WError(args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Errorf(format string, args ...any)   { W.WErrorf(format, args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Errorln(args ...any)                 { W.WErrorln(args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Fatal(args ...any)                   { W.WFatal(args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Fatalf(format string, args ...any)   { W.WFatalf(format, args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Fatalln(args ...any)                 { W.WFatalln(args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Info(args ...any)                    { W.WInfo(args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Infof(format string, args ...any)    { W.WInfof(format, args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Infoln(args ...any)                  { W.WInfoln(args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) V(l int) bool                       { return W.WV(l) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Warning(args ...any)                 { W.WWarning(args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Warningf(format string, args ...any) { W.WWarningf(format, args...) }
func (W _google_golang_org_grpc_grpclog_LoggerV2) Warningln(args ...any)               { W.WWarningln(args...) }
