// Code generated by 'yaegi extract google.golang.org/grpc/codes'. DO NOT EDIT.

package capsule

import (
	"google.golang.org/grpc/codes"
	"reflect"
)

func init() {
	Symbols["google.golang.org/grpc/codes/codes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Aborted":            reflect.ValueOf(codes.Aborted),
		"AlreadyExists":      reflect.ValueOf(codes.AlreadyExists),
		"Canceled":           reflect.ValueOf(codes.Canceled),
		"DataLoss":           reflect.ValueOf(codes.DataLoss),
		"DeadlineExceeded":   reflect.ValueOf(codes.DeadlineExceeded),
		"FailedPrecondition": reflect.ValueOf(codes.FailedPrecondition),
		"Internal":           reflect.ValueOf(codes.Internal),
		"InvalidArgument":    reflect.ValueOf(codes.InvalidArgument),
		"NotFound":           reflect.ValueOf(codes.NotFound),
		"OK":                 reflect.ValueOf(codes.OK),
		"OutOfRange":         reflect.ValueOf(codes.OutOfRange),
		"PermissionDenied":   reflect.ValueOf(codes.PermissionDenied),
		"ResourceExhausted":  reflect.ValueOf(codes.ResourceExhausted),
		"Unauthenticated":    reflect.ValueOf(codes.Unauthenticated),
		"Unavailable":        reflect.ValueOf(codes.Unavailable),
		"Unimplemented":      reflect.ValueOf(codes.Unimplemented),
		"Unknown":            reflect.ValueOf(codes.Unknown),

		// type definitions
		"Code": reflect.ValueOf((*codes.Code)(nil)),
	}
}
